### ISSUE TITLE
Implement Job State Callbacks for Condor

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#130]

**Comment by andre-merzky** [comment]
Not sure if we still deal with Condor really?

**Comment by mturilli** [comment]
Currently, we have no active use case for it. There are multiple tickets about state callback in adaptor: should we add this in the development roadmap of SAGA? Do we have facilities in place to create state callbacks in the adaptors currently in use?

**Comment by andre-merzky** [comment]
We should probably implement an inefficient, pull-based state callback mechanism in the SAGA layer, as fallback when the adaptors don't provide a more efficient one (most adaptor level implementations are just that at the moment, with lots of code replication).  

This would simplify RP code significantly, as it would remove (again replicated) code to manage pilot job state changes, so there is a good case to be made to get that on the roadmap  IMHO.

**Comment by andre-merzky** [comment]
This will be addressed in [v.2](https://github.com/radical-cybertools/radical.pilot/wiki/Roadmap-and-Milestones)
