### ISSUE TITLE
Generic Way to Determine Job Info

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#180]
There are some issues with gathering:

```
job.exit_code
job.execution_hosts
job.created
job.started
job.finished
```

The PBS (and SGE) adaptors tries to do some magic there, which mostly relies on jobs being kept in the queuing system output after they have completed. If that is not the case, they just get set to 'None'. 

There have been complaints about this before as it is not very intuitive to the user. However, there is no easy fix for this. There are already some related tickets in our issue tracker:
- https://github.com/saga-project/saga-python/issues/167
- https://github.com/saga-project/saga-python/issues/160

At some point we should try to find a way to implement this in a generic, maybe even queueing-system-independent way, maybe via a wrapper script?

**Comment by andre-merzky** [comment]
This will be addressed in [v.2](https://github.com/radical-cybertools/radical.pilot/wiki/Roadmap-and-Milestones)
