### ISSUE TITLE
job.wait() does not remove cached job information from memory

### ISSUE THREAD

**Issue by chris-zen** [radical-cybertools/saga-python#195]
In _DRMAA_ the _job.wait_ is like a _join_ for a system process, retrieves result and cleans the process from memory.

I plan to run hundred of thousand of jobs. It is not a critical amount but it would be better if they are discarded once I get the final results.

I saw this in the SGE adaptor (self.jobs dictionary), but I guess it is done the same way in the other adaptors. Just a _del self.jobs[pid]_ at the end would fix the issue, but what would happen if the user runs a get_job() again ? should we retain the job into self.jobs ?

**Comment by andre-merzky** [comment]
We are currently missing a use case which requires that type of scaling. Closing until such a  use case emerges.
