### ISSUE TITLE
Implement Callback Support for SLURM

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#239]

**Comment by andre-merzky** [comment]
This should be implemented via a state pull thread *in the API layer*, as fallback to more efficient adaptor implementations (Most adaptors just pull state...)

**Comment by andre-merzky** [comment]
This will be addressed in [v.2](https://github.com/radical-cybertools/radical.pilot/wiki/Roadmap-and-Milestones)
