### ISSUE TITLE
Job documentation missing real object attribute names and wrong descriptions

### ISSUE THREAD

**Issue by chris-zen** [radical-cybertools/saga-python#269]
I you look on the following fragment:

```
2.3.1. Attributes

saga.job.CREATED = 'Created'
str(object) -> string

Return a nice string representation of the object. If the argument is a string, the return value is the same object.

saga.job.STARTED = 'Started'
str(object) -> string

Return a nice string representation of the object. If the argument is a string, the return value is the same object.
```

1) Given a job object there is no class attribute in it named CREATED nor Created, but created.

2) Looks like the automation that transform code definitions to documentation is failing and giving always the same description: _Return a nice string representation of the object. If the argument is a string, the return value is the same object._

3) The code examples and documentation use attributes that don't really exist: job_id (instead of id), exitcode (instead of exit_code), saga.job.Pending (instead of saga.job.PENDING).

**Comment by andre-merzky** [comment]
outdated (and also fixed)
