### ISSUE TITLE
Capability checker for adaptor tests

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#29]
The adaptor tests should scan the adaptor capabilities and skip the tests that are not supported by the adaptor. run_job() in the PBS adaptor is a good example.

**Comment by andre-merzky** [comment]
This only makes sense in the context of remote testing, which needs to be revived anyway.  This is likely easier to implement via config files, as capabilities are, to some extent, also dependent on the target resource, and inspection is not able to capture this.
