### ISSUE TITLE
stalled sftp transfers

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#323]
In the use of the sftp adaptor from RP feature/staging branch I see regular blocking in transfer calls.
This is from my laptop to india. There is no apparent network issue, my ssh connection to india is still responsive at those moments.

So far I've seen two failure modes.

Mode 1: Repeating -stalled- messages:

```
2014:05:15 15:10:50 MainThread   saga.ShellDirectory   : [DEBUG   ] read : [   11] [   79] (/N/u/marksant/radical.pilot.sandbox/pilot-537   0%    0     0.0KB/s - stalled -)
```

Mode 2: "real" block, with this message as last:

```
2014:05:15 15:33:42 MainThread   saga.ShellDirectory   : [DEBUG   ] write: [   13] [   29] ( printf 'HELLO_%d_SAGA\n' 13\n)
```

I can make full logs available out of band.

**Comment by andre-merzky** [comment]
outdated.
