### ISSUE TITLE
possible documentation error

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/saga-python#346]
In 1.2.2 at:
http://saga-python.readthedocs.org/en/latest/usage/config.html#conf-options

I see a red warning but no information

**Comment by mturilli** [comment]
`usage/config.rst` will need rewriting in v.2. Meanwhile, I create a PR for this ticket that can be closed once the PR will be merged.

**Comment by andre-merzky** [comment]
Thanks @mturilli !
