### ISSUE TITLE
adaptor links are dead in documentation

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#359]
All the adaptor links on http://radical-cybertools.github.io/saga-python/index.html are dead.
Possibly related to #357?

**Comment by marksantcroos** [comment]
This is broken again. Who creates/maintains that now?

**Comment by andre-merzky** [comment]
Looks like the adaptor docs did not get built by readthedocs?  The links look ok, but the targets are obviously missing...  The buildlog at https://readthedocs.org/builds/saga-python/3080395/ indeed shows quite a number of errors -- errors which I don't see when building the docs manually (adaptor docs are then generated ok).

I guess it is me who maintains this, for the lack of anybody else :/

**Comment by andre-merzky** [comment]
outdated
