### ISSUE TITLE
LSF adaptor job status

### ISSUE THREAD

**Issue by mpbl** [radical-cybertools/saga-python#364]
Hello,

I had some issues running SAGA jobs on a LSF managed cluster.

---
##### Issue 1

From `_job_get_info` in `lsfjob.py`:

``` python
ret, out, _ = self.shell.run_sync("%s -noheader %s" % (self._commands['bjobs']['path'], pid))
```

was not working due to the `-noheader` option being unrecognized. I could not find this option in bjobs man pages as well.

Removing the `-noheader` option and changing: 

``` python`
results = out.split()
```

by

``` python
results = out.splitlines()[1].split()
```

fixed it.

---
##### Issue 2

Trying to get the job return code when it status is `DONE` was not working.
From the bjobs man page:

```
DONE The job has terminated with status of 0.
```

Adding:

``` python
if curr_info['state'] == saga.job.DONE:
    curr_info['returncode'] = 0
```

before `_job_get_info` return statement did the trick.

---
##### Issue 3

I have a loop checking for job status and launching jobs that become runnable.
Most of the time jobs were launched twice and it never happened using the pbs adaptor.
It was fixed by uncommenting:

``` python
self.jobs[job_obj]['state'] = saga.job.PENDING
job_obj._api()._attributes_i_set('state', self.jobs[job_obj]['state'], job_obj._api()._UP, True)
```

from `_job_run`, although I am not sure than uncommenting the first line alone will not have worked.

---

Hope this helps.

Best,

Matthieu

**Comment by andre-merzky** [comment]
Is this still relevant?

**Comment by mpbl** [comment]
I do not know as I do not have access to a LSF managed cluster anymore.

**Comment by andre-merzky** [comment]
I am not sure why the ticket lingered for so long, I think it simply slipped off the radar :/  Either way though, all three proposed fixes seem simple and valid to me, and I think we should apply them.  I don't think we currently have an LSF backend available for testing either though -- but the proposed patches can only make things it seems...

So, thanks again  for sending them, we'll take care of it, at long last.

**Comment by andre-merzky** [comment]
fixed.
