### ISSUE TITLE
how to deal with request % core_count != 0

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#369]
Issue #360 dealt with a failing submission on Blacklight.

Although PBS submission to Blacklight works now, the issue of core counts requests was not actually addressed yet, as can be seen in https://github.com/radical-cybertools/radical.pilot/issues/359.

Following up the discussion in #360, there is one problem I see there, and that is that if we always round up we exclude the possibility of reserving less than full nodes.

Not sure if we can completely work around that other than doing the ceil on the RP layer, which would be an awful layer violation.

A compromise on the SAGA level could be to not round up if the amount of cores constitutes less than _1_ node, but round up if the amount of requested cores is more than the number of cores in one node. We could even make it a flag ...

**Comment by andre-merzky** [comment]
What is the effort to address this?

**Comment by mturilli** [comment]
May be relevant when working on a workload manager that uses multiple pilots on multiple machines. Closing as at the moment we do not have this use case.
