### ISSUE TITLE
Support for job arrays

### ISSUE THREAD

**Issue by MaximilianHoffmann** [radical-cybertools/saga-python#373]
It would be nice to have a support to use the build in capabitliy for job arrays of SGE and pbs and others. I know that I can start job arrays with a simple python loop , but if I want to start severeal tenthousand jobs than my computer has to parse them all. Addtionally the qstat function as nice features regarding job arrays and I could us them if Saga collapses , to retrieve infromation, otherwise I have several thousand single jobs listed in the queue.

Thank you
Max

**Comment by andre-merzky** [comment]
Considered out of scope as a feature request, otherwise closing as out of date.
