### ISSUE TITLE
SFTP version not supported with recursive copying.

### ISSUE THREAD

**Issue by MaximilianHoffmann** [radical-cybertools/saga-python#374]
Sorry for posting repeatedly
Using the flag for recursive copying i get the following stack trace:

> > dir.copy('./test_dir/','sftp://localhost/',flags=2)
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/home/hoffmann/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/saga/namespace/directory.py", line 353, in copy
> >     if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype) 
> >   File "/home/hoffmann/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
> >     return sync_function (self, _args, *_kwargs)
> >   File "/home/hoffmann/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 539, in copy
> >     files_copied = self.shell.stage_from_remote (src.path, tgt.path, rec_flag)
> >   File "/home/hoffmann/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 877, in stage_from_remote
> >     raise ptye.translate_exception (e)
> > saga.exceptions.NoSuccess: sftp version not supported ( ls test_dir
> > test_dir/foo
> > sftp> mget -r  "test_dir" "/" 
> > mget: Invalid flag -r
> > sftp> ) (/home/hoffmann/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/saga/utils/pty_shell.py +1015 (run_copy_from)  :  raise se.NoSuccess._log (info['logger'], "sftp version not supported (%s)" % out))

Is there an easy work around/ have I done something wrong?

**Comment by andre-merzky** [comment]
close due to missing feedback.
