### ISSUE TITLE
Map out PBS/TORQUE landscape

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#384]
Mark suggested that we should map out the PBS / TORQUE landscape:
- What we currently support and how (flags / versions combinations)
- What else is out there

Once we have this collected, we can start deciding what options can become configurable, what can / might be detected automagically, etc. 

There's a wiki page for that: https://github.com/radical-cybertools/saga-python/wiki/PBS-TORQUE-Landscape

**Comment by mturilli** [comment]
Probably outdated by now. Most of the machines currently supported do not use PBSPro.
