### ISSUE TITLE
HPCs at NERSC (Hopper and Edison) does not identify as Crays.

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/saga-python#392]
Hi, 

After recent update of NERSC machines, 'aprun' command disappear from login nodes, so SAGA don't identify these machines as Cray any more. It cause problems with generating of PBS script with proper notation.

**Comment by andre-merzky** [comment]
Is this still a problem?

**Comment by DanilaOleynik** [comment]
Not any more. At least for me. 

Our project focused mostly on Titan and as I know NERSC migrate to SLURM.

Cheers,
Danila

**Comment by marksantcroos** [comment]
Given that Hopper is gone, Edison works (by hostname match) and I've work in progress to slash the meaningless Cray distinction in the first place, I'm going to close this ticket.

Thanks Danila!
