### ISSUE TITLE
qstat output not parsed correctly for PBSPro_12.2.1.140292

### ISSUE THREAD

**Issue by nobias** [radical-cybertools/saga-python#402]
```saga/adaptors/pbsjob.py``` parses the output from ```qstat``` (using similar code in two different functions, ```_retrieve_job()``` and ```_job_get_info()``` to get exit status, time information, etc.: It extracts a number of labels in the output of ```qstat -f``` using ```grep -E '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)'``` and later parses the associated values.

In my use case (pbs_version = PBSPro_12.2.1.140292), these labels unfortunately are slightly different:
- "Exit_status" instead of "exit_status"
- "qtime" instead of "ctime" (job submission time)
- "stime" instead of "start_time" (job start time)
- "etime" instead of "comp_time" (job completion time)

Would be nice to have these variants added to pbsjob.py. Sorry...

**Comment by andre-merzky** [comment]
Mark, can this one be closed, or is that still to do?
