### ISSUE TITLE
Entry() has is_dir()

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#408]
Shouldn't that be exclusive to Directory?

**Comment by andre-merzky** [comment]
What would be the point of that?  The implementation would then be `return True` ;)  Think of this as `test -d $SELF`, if you will...

**Comment by marksantcroos** [comment]
Currently is_dir() on File gives a NotImplemented error.

That is wrong, as it creates the impression that this is missing in the specific adaptor implentation.

**Comment by marksantcroos** [comment]
ps. Your argument doesn't make sense, as you are basically saying there shouldn't be an is_dir() for Directory either.

**Comment by andre-merzky** [comment]
On what adaptor is the is_dir missing on the file?

The expected semantics is:

```
d_1 = saga.filesystem.Directory ('file:///etc/')
f_1 = d_1.open ('passwd')

e_1 = saga.namespace.entry ('file:///etc/')
e_2 = saga.namespace.entry ('file:///etc/passwd')

assert (d_1.is_dir() == True)
assert (f_1.is_dir() == False)
assert (e_1.is_dir() == True)
assert (e_2.is_dir() == False)
```

**Comment by marksantcroos** [comment]
Does it really support your argument by not using File?

**Comment by andre-merzky** [comment]
(ve)merzky@cameo:~/saga/radical.saga (devel *$%=) $ cat t.py 
#!/usr/bin/env python

import saga

d_1 = saga.filesystem.Directory ('file:///etc/')
f_1 = saga.filesystem.File      ('file:///etc/passwd')

e_1 = saga.namespace.Entry ('file:///etc/')
e_2 = saga.namespace.Entry ('file:///etc/passwd')

assert (d_1.is_dir() == True)
assert (f_1.is_dir() == False)
assert (e_1.is_dir() == True)
assert (e_2.is_dir() == False)


(ve)merzky@cameo:~/saga/radical.saga (devel *$%=) $ python t.py 
(ve)merzky@cameo:~/saga/radical.saga (devel *$%=) $

**Comment by andre-merzky** [comment]
What is my argument to not use File?  When would you not use File?  I am confused...

**Comment by marksantcroos** [comment]
Im talking specifically about File and you create examples that dont use it.

**Comment by marksantcroos** [comment]
Ok, sorry. You did use File in one of them. Apologies.

But back to the original point, you consider is_dir() a valid method for a File object? If so, why?

**Comment by andre-merzky** [comment]
`is_dir()` is a method on an `namespace.Entry` object, so that if you get a handle to one, or open one with an URL without knowing any details, you can check if it is an dir, *or not*.  This is not a replacement for `isinstance (self, saga.namespace.Directory)`!

```
def my_fancy_list (url, indent=0) :
    indent += 2
    print ' '*indent,
    e = saga.namespace.Entry (url)
    if e.is_dir():
        print " -> %s/" % url.path
        d = saga.namespace.Directory (url)
        for sub in d.list():
             my_fancy_list (indent, sub)
    elif e.is_link():
        print "  > %s/ -> %s" % (url.path, e.get_link())
    else:
        print "  - %s" % url.path
```

Both filesystem.File and filesystem.Directory inherit from namespace.Entry -- so you can write generic methods which operate on Entries, or URLs, like the one above...

**Comment by marksantcroos** [comment]
Thanks. I agree it makes sense that both Directory and File inherit from Entry.
To me its still not super intuitive that File also has the method, but its a minor annoyance :-)
