### ISSUE TITLE
url parsing: distinguishing files from directories

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#409]
Take the following code snippet: 
```
>>> a = 'sftp://edison.nersc.gov/tmp/go'
>>> Url(a).path
'/tmp/go'
>>> a = 'sftp://edison.nersc.gov/tmp/go/'
>>> Url(a).path
'/tmp/go'
```

Is this expected?

I.e. should/would it be possible to derive file/directory status from just URL convention alone or is it by definition always necessary to check with the backend? (The latter is problematic when its about something that doesnt exist yet)

Context: When I specify a target location, I want to be able to specify a directory only, and use the same filename as the filename in the source. If the target also specifies a file, then I would like to use that filename. Is SAGA supposed to be able to do this, or should this logic be on top of SAGA and should the target always include a filename?

**Comment by andre-merzky** [comment]
The slash removal seems to come from `os.path.normpath` which we apply to URL path elements.  The different URL parsers around seem to disagree on path normalization -- but the RFC seems to suggest that the trailing slash should be left alone.  So I committed a fix to utils which preserves the trailing slash now.

**Comment by marksantcroos** [comment]
Seems to work as advertised, thanks!
