### ISSUE TITLE
x509 context should probably pickup $X509_USER_PROXY instead of trying to guess the filename

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#413]
Would make at least the examples more portable.

**Comment by andre-merzky** [comment]
This is implemented now -- thanks!

**Comment by marksantcroos** [comment]
Cool, looks good. Thanks!

**Comment by marksantcroos** [comment]
Lets wait with closing until I tried it though, there seems to be more to it.

**Comment by marksantcroos** [comment]
Ok, it works! (kind of ;-)

I still had my add_context() around, which was empty besides its type.
Given the name "add", and not "set", I figured this would be ok.
Then I started looking at the code and that had so many red herrings that I figured something was wrong.

This might benefit from some cleanup and documentation.

**Comment by andre-merzky** [comment]
'add' should indeed 'add' the context:

https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/session.py#L275

If that does not  yield the expected result, please do open a new ticket!  That would likely be an adaptor level problem: the adaptor needs to make sure it is looking through all contexts of the session...
