### ISSUE TITLE
monitoring channel failed -- disable notifications

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#416]
With the current SAGA Python master branch, I see the following error:
```
2015:03:09 13:01:22 27252  Thread-93    saga.ShellJobService  : [ERROR   ] monitoring channel failed -- disable notifications
```
I’m not quite sure if this is really an ERROR, as execution seems to work ok as far as I can tell. HOWEVER, at least our Jenkins tests seem to hang indefinitely due to this issue:

http://ci.radical-project.org/job/EnsembleMD/168/PYTHON=System-CPython-2.7,RADICAL_STACK=PYPI/console.

It also seems that the same issue has made it into the PyPi release:

http://ci.radical-project.org/job/EnsembleMD/PYTHON=System-CPython-2.7,RADICAL_STACK=PYPI/165/console

**Comment by andre-merzky** [comment]
This should be addressed by now, via the ssh channel leases.
