### ISSUE TITLE
Make optional SSH fallback (in .saga.cfg) default

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/saga-python#418]
via email:

I am forwarding this email to the list so that the issue doesn’t fall of the radar. I think several users (+ me) are strongly in favor of adding “the fix” as a default option to SAGA-Python. Explicitly disabling it can be controlled via .saga.cfg as opposed to the other way around. 

in reply to:

Hi all,
I raised a whole bunch of issues for stuff which came up during the testing, most of which are trivial to fix.  We should also think about whether the .saga.cfg SSH fix should become the default behaviour.
Unfortunately I’m attending a meeting for the next few days and then on leave for the following week.  I suggest we schedule a call for Mon 20th, 3pm UK time to catch up.  If we can work through the issue log before then that would be great.
- Iain

**Comment by ibethune** [comment]
Implemented, already.
