### ISSUE TITLE
ssh authentication reuse

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#419]
At some point in time, I could get away with giving my token once or twice to get RP going.
Now it takes one for every connection with makes it practically unusable.

Is this an intentional change?

**Comment by andre-merzky** [comment]
The only change I can think of which triggers this is disabled connection sharing.  I doubt you are running on CentOS -- but do you have that flagged in your ~/.saga.cfg?

**Comment by marksantcroos** [comment]
I didn't. Also setting explicitly to "yes" doesn't make a difference.

**Comment by marksantcroos** [comment]
By manually exercising the commands I get:

```
"mux_client_request_session: session request failed: Session open refused by peer"
```

I'm afraid we have to conclude that Titan doesn't like multiplexing ...

Probably unrelated, but it seems that both Master and Slave use `ControlMaster=yes`, isnt that wrong?

**Comment by andre-merzky** [comment]
Damned on Titan :(

I am not sure why share_mode would be 'yes' -- it should be 'auto' on both, that is the default for the setting: https://github.com/radical-cybertools/saga-python/blob/master/src/saga/engine/engine.py#L26  Does the log or anything tell you where 'yes' is set as option?

**Comment by andre-merzky** [comment]
Actually, the `yes` might be related to your problem, as it makes all connections behave like master connections... ?

**Comment by marksantcroos** [comment]
Maybe that output was from the time that I had configured the "yes" in my .saga.cfg.
Let me check that.

**Comment by marksantcroos** [comment]
Ok, that was a red herring. Its auto indeed.

**Comment by marksantcroos** [comment]
> Actually, the yes might be related to your problem, as it makes all connections behave like master connections... ?

No, I only tried that after it didn't work.
Same effect as with auto.

**Comment by marksantcroos** [comment]
Practically, if I manage to do all transfers out-of-bound, whats left?
Will there be one session to submit the job and monitor that, or will there be a new connection for every monitor activity, etc?

**Comment by andre-merzky** [comment]
I implemented job.Service caching in the pilot monitoring thread a while back, if that is still working, it should only be one connection per pilot monitor -- but another one for staging of the agent sources etc., and one for starting the pilot.  Also, I think the SAGA layer still runs the master session, even if it is not used for sharing.  

Having said that, SAGA internally uses a connection pool, so if some of the things happen in sequence (vs. concurrently), sessions get reused, so the count may be lower.

The SAGA level code is pretty much tailored toward sharing and reuse at this point though, interactive passphrase/PIN/... entering is not something I optimized against :/

**Comment by marksantcroos** [comment]
I can likely offload all transfers to GO. So a handful of interactions might be bearable, but this likely needs a more "real" solution.

**Comment by marksantcroos** [comment]
The mux errors seem to be non-fatal ultimately .. can you explain that?

**Comment by andre-merzky** [comment]
I have seen `mux_client_request` errors which lead to connection errors, and also some which do not.  I am not exactly sure, but my assumption is that some ssh versions (probably more recent ones) fall transparently back onto unshared connections if shared ones do not work.

**Comment by marksantcroos** [comment]
Yes, this was a case of "doh" which I figured out offline already :-)
(I didn't realize it earlier because the gazillion of token prompts made that I didn't went through with it)
Sorry for the noise!

**Comment by andre-merzky** [comment]
np :)
