### ISSUE TITLE
Excessive polling of PBS server

### ISSUE THREAD

**Issue by capaulson** [radical-cybertools/saga-python#420]
I have a script that I use to take jobs from a database and run them on a cluster. This morning, I received notification that this script had caused significant issues with the PBS server. At the time, I was using saga-python to monitor 50 jobs, each in an individual thread. The code executed in each thread is: 

```python
js = saga.job.Service("someserver")
jd = saga.job.Description()
#other job configuration tasks go here... 
catjob = js.create_job(jd)
catjob.run()
print "Job ID : %s" % (catjob.id)
print "Job State : %s" % (catjob.state)
catjob.wait()
print "Job ID: %s" % (catjob.id)
print "Job State : %s" % (catjob.state)
print "Exitcode : %s" % (catjob.exit_code)
js.close()
```

After approximately 24 hours of the script running, the PBS server started not responding to other users. The cluster admins informed me that I had tied up over 25,000 TCP ports, effectively DOSing other users. I would like to understand if this is expected behavior for saga-python, and if so, how do I tune the level of polling?

**Comment by andre-merzky** [comment]
Woah, that is certainly *not* the expected behavior!  I'll look into that, thanks for the report.  `js.close()` should tear those monitoring threads down.

Having said that, creating a service instance is a very costly operation, both in terms of time it needs to set up the connection, and in terms of resources used on both ends.  Is there any specific reason that prevents you from re-using the `job.Service` instance for the individual jobs?

**Comment by capaulson** [comment]
I can't recall why job.Service is called inside. I use a multiprocessing pool for the script, so there may have been some issue there? I'll look into why I did that and get back to you. 

Thanks for looking into the issue. Please let me know if I can provide any additional details that would help diagnose this.

**Comment by andre-merzky** [comment]
Hi again, 

So far, I did not manage to reproduce the problem.  I have been running a test script against a torque version 2.5.5 (which uses the PBS adaptor), and could not see any lingering threads nor connections.  

Would you mind providing some additional information?  

  * specific pbs flavor / version
  * version of the ssh daemon on the target machine
  * version of the ssh command on the client machine
  * possibly some complete code which reproduces the problem for you

?  Many thanks, Andre.

**Comment by andre-merzky** [comment]
I should have added: it would also be useful if you could run under `SAGA_VERBOSE=DEBUG`, and then send the resulting debug output.  Its probably too large to paste here, so a download pointer or GIST upload would be great...  Thanks!

**Comment by marksantcroos** [comment]
Do we know whether the reported TCP connections are connection to the PBS server or SSH connections?
That would be the first thing to find out.

**Comment by capaulson** [comment]
Hi, 

The script I was running before ran on a cluster headnode, running in a Screen environment. The call for the job.Service call looks like: ```js = saga.job.Service("pbs://<user>@localhost")```

The full script is below. It's not really easy to reproduce, as the script automatically pulls geometries from a database and builds a simulation job for each new entry. I think the only bit of code missing is the 'file_adapter' stuff, but this is just a class to simplify access to a MongoDB instance. I'm compiling the other information now.  

```python
import saga
import os, sys
import shutil
import file_adapter

from multiprocessing import Process, Lock, Pool, Value
import itertools
import time


transferLock = Lock()
filesystemLock = Lock()

def runSimulation(id):
    a = file_adapter.dbUtil()
    a.openDB(server='mongodb://<server>')
    entry = a.findOne({'_id':id})
    
    
    
    #Setup a folder on the local directory
    with filesystemLock:
        try:
            if not os.path.exists('tmp/%s'%a.id):
                os.mkdir('tmp/%s'%a.id)
            if not os.path.exists('tmp/%s/%s'%(a.id,id)):
                os.mkdir('tmp/%s/%s'%(a.id,id))
        except:
            #record error and return
            print 'Error!!! (entry: %s)'%id
            a.updateEntry(entry['_id'], entry)

    # Extract the STEP File
    try:
        with transferLock:
            a.recoverSTLFile(entry['_id'],path='tmp/%s/%s'%(a.id ,entry['_id']))
        except:
            #mark and error and return
            print 'Error!!! (entry: %s)'%id
            a.updateEntry(entry['_id'], entry)
            return id

    # Setup the filePath for the temp files on the local machine
    #print a.db, entry['_id']
    shutil.copy('Template/run', 'tmp/%s/%s'%(a.id ,entry['_id']) )

    localSRC = 'tmp/%s/%s'%(a.id,id)
    remoteDST = 'data/%s/'%a.id
    cmd = 'cp -r %s %s'%(localSRC, remoteDST)
    with transferLock:
        print os.system(cmd)
    
    #Launch the PBS job and wait
    print 'creating saga service'
    with transferLock:
        js = saga.job.Service("pbs://<user>@localhost")
    if not js:
        return None
    print 'creating saga job'
    jd = saga.job.Description()
    jd.working_directory = 'data/%s/%s/'%(a.id, entry['_id'])
    jd.wall_time_limit = 16*60# minutes
    jd.total_cpu_count = 16
    jd.environment = {'NODES': '%d'%jd.total_cpu_count}
    jd.executable = './run'
    jd.output = "saga_localjob.stdout"
    jd.error = "saga_localjob.stderr"
    
    # create the job (state: New)l
    print 'creating job'
    with transferLock:
        catjob = js.create_job(jd)
        time.sleep(5)
    
    print "\n...starting job...\n"
    catjob.run()

    print "Job ID : %s" % (catjob.id)
    print "Job State : %s" % (catjob.state)

    catjob.wait()
    print "Job ID: %s" % (catjob.id)
    print "Job State : %s" % (catjob.state)
    print "Exitcode : %s" % (catjob.exit_code)
    js.close()

    #Process the results
    #Store the results to file
    #Update and close out the database entry
    #Change the tracking flags to reflect the status of the run
    a.updateEntry(entry['_id'], entry)
    a.close()
    return id

def callback(id):
    print 'Job {} has finished'.format(id)

pool = Pool(50)
a = file_adapter.dbUtil()
a.openDB(server='mongodb://<server>')
searchParams = {something}
count = 0

while True:
    time.sleep(.1)
    if len(pool._cache) < (pool._processes  + 2) and not pool._state:
        with transferLock:
            entry = a.findOne(searchParams)
            if entry is None:
                time.sleep(60)
                count +=1
                #Close the pool if no new entries found in over a day
                if count > 3600:
                    pool.close()
            else:
                count = 0
                # Change db flags to indicate job is running
                a.updateEntry(entry['_id'], entry)

    req = pool.apply_async(runSimulation, args = (entry['_id'],), callback=callback)

pool.join() 
```

**Comment by capaulson** [comment]
Currently, the cluster is running Adaptive Computing's Moab HPC Suite 7.2.9 on RHEL6. The ssh version on the machine is ```OpenSSH_5.3p1, OpenSSL 1.0.0-fips 29 Mar 2010```

I'll run something with a verbose flag soon, but I want to coordinate with the cluster admins, as I don't want to interrupt the cluster again. Unfortunately I'm traveling at the moment and happen to be 8 hours off, so that coordination is tricky.

**Comment by capaulson** [comment]
One other note from the admin: What I found yesterday that there were 25,000+ sockets to Iridis4_a in a TIME_WAIT state after connecting to the PBS server. Basically the port is not closed immediately after qstat has the info it needs from the server, and may linger around for up to 4 mins afterwards, just in case there are any stray TCP packets for that port hanging around on the network.

**Comment by andre-merzky** [comment]
Many thanks for the details -- that helps a lot!  So, as Mark also suggested, it is not ssh connections which hang around, but TCP ports used by qstat... That is unexpected...

I'm afraid I can't give you a quick workaround, but will get back to you ASAP.

Don't worry about the traces at this point, we should have enough info for now -- thanks!

**Comment by capaulson** [comment]
Hey Andre, 
Just wanted to check if any progress had been made on this?
Cheers!

**Comment by andre-merzky** [comment]
Hi -- we did not yet manage to reproduce the problem, I'm afraid.  I pinged Adaptive Computing for an evaluation version of the MOAB HPC suite, but didn't hear back, yet.  I'll ping them again, thanks for the reminder!

**Comment by capaulson** [comment]
Ok, if there is anything I can help with let me know. I have access to MOAB HPC :).

**Comment by andre-merzky** [comment]
Hi again, 

I did again get no reply from AC -- would it be possible to get access to your cluster, by any chance?  I don't intent to run large loads, but rather inspect what happens to individual submissions (which seem to trigger the qstats  too often)...

-------------------------------------------

On a tangent, I wanted to ask you something different.  In the script you included above, it lloks like the purpose is to run a (relatively) large number of simulations concurrently?  (You use a multiprocess pool to have 50 of those small simulation managers running where each of them watches over one simulation on the cluster.)

Now, we happen to work on a very similar set of problems, where we execute large numbers of independent (relatively small) jobs on a large HPC resource, but implement that in a more generic way, via a pilot based approach.  Generic approaches is what we do, as you might have guessed from SAGA :)

I think that this actually matches exactly your use case, and you may want to have a look at https://github.com/radical-cybertools/radical.pilot/ .  This is not to say that the SAGA approach  wouldn't work, or that the bug doesn't need fixing -- but the radical.pilot is very likely to give you simpler code and (much) better overall performance.  One caveat: we use hard coded configuration files for all clusters we support, and your target is not on our list.  http://radicalpilot.readthedocs.org/en/latest/machconf.html#writing-a-custom-resource-configuration-file describes how to add cluster configurations -- but if you are interested, drop us a note, and we are happy to help with that config!

**Comment by capaulson** [comment]
I'm unfortunately unable to give you direct access to the cluster, but we may be able to work something else out. Can you shoot me an [email](http://cmg.soton.ac.uk/people/cp1m11/) to discuss this off github?

I'll take a look at radical.pilot, sounds interesting.

**Comment by andre-merzky** [comment]
Hi @capaulson, 

I am not exactly sure how to proceed with that ticket, but wanted to check if the radical-pilot route looked interesting enough to consider to switch?

**Comment by andre-merzky** [comment]
We will be closing this ticket due to inactivity -- but please feel free to re-open if you think we can make some progress!
