### ISSUE TITLE
sge:  error 27: searching requested shell"

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#434]
```
2015:07:16 19:50:04 2470   MainThread   saga.PTYShell         : [DEBUG   ] read : [    4] [  201] (hostname     node374             \nqsub_time    Thu Jul 16 19:48:55 2015\nstart_time   -/-\nend_time     -/-\nfailed       27  : searching requested shell\nexit_status  0                   \nPROMPT-0->)
2015:07:16 19:50:04 2470   MainThread   saga.SGEJobService    : [DEBUG   ] job_info(5228838)=[state=Failed, returncode=0, exec_hosts=node374, create_time=Thu Jul 16 19:48:55 2015, start_time=-/-, end_time=-/-, gone=False]
```

**Comment by marksantcroos** [comment]
Hi Robert,

Would you mind giving the https://github.com/radical-cybertools/saga-python/tree/issue/434 branch a try?

Thanks!

Mark

**Comment by SmokinCaterpillar** [comment]
Hi Mark,

same result as already discussed on the mailing list. After submitting the job it still ends up in the `Eqw` state.

Debug file can be found [HERE](http://s000.tinyupload.com/?file_id=57810743713970211122).

**Comment by marksantcroos** [comment]
I just pushed another attempt to the branch.
But after looking at your debug log again, it seems you actually didn't run from master.
Can you verify you installed the right version?
(e.g. `pip uninstall saga-python && pip install -e git://github.com/saga-project/saga-python.git@issue/434#egg=saga-python`)
Thanks!
(you can try the latest, if that doesnt work, I'll revert the latest commit to try that again)

**Comment by marksantcroos** [comment]
One other thing. Does the system not allow you to look at finished jobs? That's how it seems, but maybe there is another way that you (can) use?

**Comment by SmokinCaterpillar** [comment]
Yes, sometimes Saga Python is able to determine the start and end times of the jobs and sometimes not, if this is what you mean by being not allowed to look at finished jobs. But I always check manually via `ssh` and `qstat -j <jobnumber>'.
Which again outputs:

``error reason    1:          07/20/2015 08:35:01 [35257:3530]: execvlp(/var/spool/sge/node115/job_scripts/5391390, "/var/spool/sg
``

and the job summary says:


job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------      
5391390 1.00004 SAGA-Pytho augustin     Eqw   07/20/2015 08:34:58                                    1 ``

I reinstalled saga-python as you suggested, [HERE ist the debug output](http://s000.tinyupload.com/?file_id=02684283091332141391) .

**Comment by marksantcroos** [comment]
> Yes, sometimes Saga Python is able to determine the start and end times of the jobs and sometimes not, if this is what you mean by being not allowed to look at finished jobs. But I always check manually via ssh and `qstat -j <jobnumber>'.

Right, I meant the latter, thats good to know, as SAGA is using qacct to get the info, and failing in that.
We need to change it to first try to use qstat and only if that fails, fall back to qacct, I think.

> error reason 1: 07/20/2015 08:35:01 [35257:3530]: execvlp(/var/spool/sge/node115/job_scripts/5391390, "/var/spool/sg

This doesn't help with the assessment of the root cause though. Any chance that you could get more information out of that qstat call in a more verbose mode or so?

Alternatively, would you be able to give us access to an account on your cluster for debugging purposes?

**Comment by SmokinCaterpillar** [comment]
I am currently at a conference, so I can only look into this occasionally :-)

Hmm is there a more verbose version of ``qstat``? I looked through the man pages, but could not find anything. I can provide the output for ``qacct`` nonetheless. And here also it says ``searching requested shell``:

==============================================================
qname        short               
hostname     node241             
group        informatik          
owner        augustin            
project      NONE                
department   defaultdepartment   
jobname      SAGA-Python-SGEJobScript.FoKxTb
jobnumber    5440801             
taskid       undefined
account      TG-MCB090174        
priority     0                   
qsub_time    Thu Jul 23 11:12:07 2015
start_time   -/-
end_time     -/-
granted_pe   mp                  
slots        1                   
failed       27  : searching requested shell
exit_status  0                   
ru_wallclock 0            
ru_utime     0.000        
ru_stime     0.000        
ru_maxrss    0                   
ru_ixrss     0                   
ru_ismrss    0                   
ru_idrss     0                   
ru_isrss     0                   
ru_minflt    0                   
ru_majflt    0                   
ru_nswap     0                   
ru_inblock   0                   
ru_oublock   0                   
ru_msgsnd    0                   
ru_msgrcv    0                   
ru_nsignals  0                   
ru_nvcsw     0                   
ru_nivcsw    0                   
cpu          0.000        
mem          0.000             
io           0.000             
iow          0.000             
maxvmem      0.000
arid         undefined

======================

Anyway, I am sorry, but I am not in a position to grant you access to our cluster. However, when I return home (in two weeks) I can ask the staff if this is possible.

**Comment by marksantcroos** [comment]
Another longshot, can you try to remove the "jd.project" from the job description?

Otherwise I think we need to wait until you get back home.

**Comment by SmokinCaterpillar** [comment]
No, sorry, makes no difference, fails as before.

**Comment by SmokinCaterpillar** [comment]
Short unsatisfying update: I am back but everyone else is on holiday. Anyway, I don't think you can get access, in the internal handbook it states that **only** members of the University are allowed to access the Cluster. But I'll give you an update as soon as I know more :-).

**Comment by andre-merzky** [comment]
Thanks for the update though! :)

**Comment by andre-merzky** [comment]
Hey @SmokinCaterpillar , and news? :)  Thanks!

**Comment by SmokinCaterpillar** [comment]
I'm afraid not :-(

**Comment by andre-merzky** [comment]
Hi Robert, 

I had a (couple of) wild guess(es) and pushed another commit to the  https://github.com/radical-cybertools/saga-python/tree/issue/434 branch -- would you mind giving it a try?

Another question: is there any user manual or operation manual available for the cluster you are using?

Thanks, Andre.

**Comment by andre-merzky** [comment]
One more question, if you don't mind: what is the OS of your *local* machine which  runs the SAGA script?

**Comment by andre-merzky** [comment]
This ticket has unfortunately been silent for several month.  I'll close it, but please feel free to reopen if it becomes relevant again!

**Comment by SmokinCaterpillar** [comment]
Sorry, honestly I totally forgot about it, I am really busy atm finishing my degree. But I'll look into it again in May, but I can't any time sooner :-)

**Comment by andre-merzky** [comment]
No worries, thanks for the update!  Good luck with your degree :)

**Comment by andre-merzky** [comment]
closing issue doe to lack of activity.

**Comment by stverhae** [comment]
just wanted to let you know:  I got the same error in sge (no extra libs), and was resolved by fixing the permissions (+x) of the executables I was trying to run ...
