### ISSUE TITLE
properly deal with processes_per_host in all job adaptors

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#443]
See discussion in https://github.com/radical-cybertools/saga-python/pull/442

**Comment by andre-merzky** [comment]
Which adaptors are actually missing support at this point?

**Comment by vivek-bala** [comment]
Based on #442 , it hasn't been implemented for Slurm and Torque (out of the adaptors we commonly use). @andre-merzky  how do you want to proceed?

**Comment by andre-merzky** [comment]
This actually is supported by slurm and torque by now.
