### ISSUE TITLE
TypeError from make_dir() when specifying directory name that already exists

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#449]
Missing tuple around format string parameters in `make_dir()` in [shell_file.py](https://github.com/radical-cybertools/saga-python/blob/407dae441f5031e09f0ea11c3d62466027933171/src/saga/adaptors/shell/shell_file.py#L757) results in a `TypeError` when trying to create a directory that already exists. Expected behaviour is for this to raise a `saga.NoSuccess` exception. e.g.

```
import saga
from saga.filesystem import Directory
ctx = saga.Context("ssh")
ctx.user_id = 'myuser'
ctx.user_key = '/home/myuser/.ssh/my_key'
sn = saga.Session()
sn.add_context(ctx)
dir = Directory('sftp://localhost/tmp/')
dir.make_dir('test')
dir.make_dir('test')
```

-> `TypeError: not enough arguments for format string`

**Comment by andre-merzky** [comment]
Thanks,  nice catch!  The fix will be merged into devel shortly, and will make it into the next release.

Thanks again, Andre.
