### ISSUE TITLE
Add FILE_TRANSFER support for ssh job

### ISSUE THREAD

**Issue by Francis-Liu** [radical-cybertools/saga-python#453]
I think the "saga.job.FILE_TRANSFER" attribute would be much more convenient to use than the "saga.filesystem.File.copy()". However, that attribute seems not supported for "ssh" type of job.

**Comment by marksantcroos** [comment]
Hi Francis, good point.
This is related to #298, where @andre-merzky claims that "ssh" already supports it, but I dont actually see it in the code.

**Comment by andre-merzky** [comment]
Sorry if the comment in #298 is confusing... -- the underlying PTY layer supports the transfer, but it is not being used in the ssh adaptor (nor most other job adaptors), yet.

Francis, agree that this should get implemented, and indeed is much more convenient than explicit file transfers, but I am not sure when we'll find the time to add it...

**Comment by vivek-bala** [comment]
I believe this is already implemented although I don't see any commit/PR referenced. @andre-merzky can you confirm please?

**Comment by andre-merzky** [comment]
Yes, this is implemented for the shell adaptor (which also covers ssh and gsissh).
