### ISSUE TITLE
re-interpretation of COMPLETING states

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#469]
See radical-cybertools/radical.pilot/pull/468

> In Slurm, I opened a PR to have the equivalent of E (CG) interpreted as CANCELED, because at this ?
> point it is inevitable that the job will finish, and it can stay in CG rather long for some reason, at least on 
> BW and Stampede, and thus the RP shutdown is delayed quite a bit. This is semantically not fully ? 
> correct though. Either way, we should keep it consistent I guess, and either purge the slurm PR, or also 
> use that interpretation here and in the other adaptors.

and radical-cybertools/saga-python/pull/467

> The job got the cancellation command, it just takes some time to clean the nodes it seems (slow FS?). 
> So, accept this, and move on.

**Comment by marksantcroos** [comment]
I think while your comparison of `CG` on SLURM to `E` on TORQUE is correct, bringing in the `C` of Blue Waters is unrelated and confusing.

On SLURM, you get `CG` on both cancelation and normal completion. So IMHO we really can't just translate that to `CANCELED`.

On BW, the epilogue actually is performed during the `R` state, and after that it goes into `C`, which we interpret as `DONE`,`FAILED` or `CANCELED`, depending on the exit code. I never see `E` there. (I believe we do see it on ARCHER, but then again, thats a PBS Pro installation.

**Comment by andre-merzky** [comment]
Thanks for the clarification!  That will then need a more nuanced approach, if we want to tackle at all...

**Comment by andre-merzky** [comment]
close as invalid.
