### ISSUE TITLE
Service does not propagate session object to shell adaptor

### ISSUE THREAD

**Issue by mehdisadeghi** [radical-cybertools/saga-python#477]
I am creating Service objects with *userpass* security context. While doing so I realized that folder creation fails on remote hosts. After investigation it seems that [the way](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fradical-cybertools%2Fsaga-python%2Fissues%2Fnew) *saga.base.Base* initializes the adaptor is the problem.

    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)

The above method call fails to propagate the *session* arguement to the underlying *shell adaptor* instance, as the *init_instance* [method](https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/shell/shell_file.py#L257) is implemented differently.

    def init_instance (self, adaptor_state, url, flags, session) :

To reproduce the problem take these steps:

    >>> js = saga.job.Service("ssh://joe2")
    >>> js.session == None
    True
    >>> ctx = saga.Context("ssh")
    >>> session = saga.Session()
    >>> session.add_context(ctx)
    >>> js = saga.job.Service("ssh://joe2", session=session)
    >>> js.session == None
    True

It seems that the session is always empty, no matter which context I do use. However, setting the session explicitly on the underlying adaptor solves the problem:

    >>> js._adaptor._set_session(session)
    >>> js.get_session()
    <saga.session.Session object at 0x286c950>

I can send you a PR in case you approve this issue.

**Comment by andre-merzky** [comment]
Hi Mehdi - long time no see :)

> The above method call fails to propagate the session argument to the underlying shell adaptor instance

duh, how did I manage to mess this one up?  Yes, a PR would be great for this one, very much appreciated!

Thanks, Andre

**Comment by mehdisadeghi** [comment]
Yes, right, it has been a long time, I'll be more active again! :-)

And soon l'll send the PR.
