### ISSUE TITLE
os.read EIO + Received message too long error 

### ISSUE THREAD

**Issue by mehdisadeghi** [radical-cybertools/saga-python#482]
One of our users get an error while trying to get job service instance. Here is the [pastebin version](http://pastebin.com/RbxDGUQJ) of the error and the error text:

    NoSuccess: read from process failed '[Errno 5] Input/output error' : (Received message too long 795178083 ) (/W5/sade/workspace/saga-python/src/saga/utils/pty_process.py +679 (read) : % (e, self.tail)))

By the way, connecting to the same host with my own user, I don't get this error message.

I tried to find where the error exactly comes from, actually it comes from an `os.read` call in `pty_process.py` module line 600:

    buf  = os.read (f, _CHUNKSIZE)

I see that SAGA wants to copy `shell_wrapper.sh` file from user's home directory to the remote machine. I guess there might be an error in our networked filesystem, since we use nasp and not local disks. Since only one user gets this error it could be the case that this specific user has some errors in his home directory. 

I wonder why SAGA writes the source file onto disk and inside user's home directory instead of getting a tempfile from operating system. Moreover why does it need to write a file to disk when it is already loaded into the memory (I see while debugging that the shell_wrapper.py is already loaded into a python variable).

I appreciate any idea on this problem.

P.S. There is also a similar issue #403

**Comment by marksantcroos** [comment]
Could it be that the user has some special things in its bash .profile / .bashrc that pops up at login and confuses sftp?

**Comment by mehdisadeghi** [comment]
It could be the case. We have many custom scripts which are loaded on ssh login. Here is the output shoed on ssh login:

    pc-p282(/W5/sade/workspace) ssh pc-p115
    Password: 
    Last login: Wed Nov 18 16:46:52 2015 from console
    Have a lot of fun...
    /etc/bash.bashrc.local von -bash gerufen.
    /usr/local/syslogin.sh von -bash gerufen.
    /usr/local/sysnames.sh von -bash gerufen.
    /usr/local/aliases.sh von -bash gerufen.
    /home/ras/.bashrc von -bash gerufen, HOSTTYPE = x86_64
    load Compiler xe_2013_sp1 intel/XE.2013 x86_64 to/from yourPATH
    load MPI mpi/open x86_64 to/from your PATH
    ~/.profile von -bash gerufen.

I put a print statement in `read` method of `pty_process.py` and I tried to print `self.tail`. I can see that this method (read) is being called hunderds of times and reads each line of ssh output many times. The login welcome message alone appears more than 40 times and then everything else. Here is a (sample)[http://pastebin.com/UddHfKX8].

**Comment by andre-merzky** [comment]
There is no specific reason to write the shell script to `$HOME/saga/...`, other than that this makes it easy  to debug things, and keep the tree separated for users.  Creating a dir in `/tmp/` would also work, absolutely, and on some machines would probably also make a performance difference.  I would not mind if we add that location as an adaptor config option, or event make `/tmp/` the default.

Having said that, I don't think that this is the fundamental problem -- this really looks more like a problem on dealing with the shell output on connection setup (as usual :-( ).  I am not sure I understand whats up with the repeated reads of the same data...

We are talking about the read op at this place:
https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/utils/pty_process.py#L600
right?  So, that read returns the same `buf` over and over again?  Would you mind adding a `buf=None` just before that read, and check whats happening?  Should not be needed, but...

Thanks!

**Comment by mehdisadeghi** [comment]
Hi Andre!

I added `buf=None` before that line but it did not change anything :(. 

BTW whatever I have explained above including my hypotheses about filesystem errors might be wrong, since these parts of SAGA are complicated and I still lack the big picture.

I tried to add an echo statement to my own shell startup scripts to have a similar login message and I was able to login using saga. I tried then to put some print statements inside `read` method and I realized even though I get no pty errors, but the same repetitive behavior happens. Surprisingly after putting print statements the pattern pty process never ends its execution, probably due to some extra delays. It might be the case that saga is repeating read operation to find the right pattern but it never ends doing so...

I will update if I find anything new, still digging deeper...

**Comment by mehdisadeghi** [comment]
I see people are complaining on internet that this is a sftp/scp issue. It doesn't like welcoming messages or anything like that apparently.

I also found that saga makes a control file and when I tried to use that file to do sftp I got the same error:

    pc-p282(~) sftp -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_sade_%h_%p.ras.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 sade@xeo51
    Received message too long 795178083

I'm not sure if this error could be prevented by saga at all.

**Comment by marksantcroos** [comment]
> I'm not sure if this error could be prevented by saga at all.

Right, I think this error is generally a sign of sftp swallowing on verbose output from the shell environment.

**Comment by andre-merzky** [comment]
So, where does this leave us?

**Comment by mehdisadeghi** [comment]
Tomorrow I will make sure that this error goes away if the same user (who
had this problem) can make sftp to the same remote machine then we can
close this issue. And for infinite I/O read loop I have no idea, it might
be because of sftp as well.

**Comment by andre-merzky** [comment]
The `read()` thingie confuses me more than the message size problem, to be honest, but I also have no clear idea what to do about it.  The read is a rather low level a python call, and there is not much open to interpretation about it I would think...

Anyway, thanks for the followup -- please let us know if you can work around it...

**Comment by mehdisadeghi** [comment]
So, good news is that the problem solved! We realized that the given user had some sort of `verbose` login flag in his home directory and that was producing tons of log output. Moreover, we tried to do `scp` and it failed without raising some proper error message. After disabling verbose mode, every thing went back to normal! I close this issue now.

**Comment by marksantcroos** [comment]
Pfew, thanks!

**Comment by andre-merzky** [comment]
'Pfew' indeed! :)
