### ISSUE TITLE
Saga proxy command

### ISSUE THREAD

**Issue by jvegasbsc** [radical-cybertools/saga-python#485]
Hi

We are trying to connect to a machine using SSH that is only accessible by a proxy:
```
Host HPC
	ProxyCommand ssh -q FIREWALL nc HPC 22
	User user
	GSSAPIAuthentication no

Host FIREWALL
	HostName firewall.host.name
	Port 36325
	User firewalluser
	IdentityFile ~/.ssh/key
	GSSAPIAuthentication no
```

We don't know how to specify the proxy command in SAGA. Can you help us, please?

Thank you in advance for your help,
Javi

**Comment by marksantcroos** [comment]
Hi Javi,

I would actually suggest to hide the details of that in your ssh config.
Or doesnt that work?

Regards,

Mark

**Comment by jvegasbsc** [comment]
Hi Mark,

That does not work. In fact, the code in the first message it's the ssh config with the names and urls changed

Regards,
Javi

**Comment by marksantcroos** [comment]
> In fact, the code in the first message it's the ssh config with the names and urls changed

Sorry, I don't understand what you mean with this. Can you please elaborate?

**Comment by andre-merzky** [comment]
SAGA is not able to handle ssh proxies I'm afraid.  I agree with Mark, setting up the ssh config is your best bet.  You said that the entries you posted above seem not to work.  Are those settings functional when you run ssh on command line?  If so, could you please paste the command you tested with, and also the URL you are using in the SAGA code?  Thanks!

**Comment by jvegasbsc** [comment]
I don know how, but now it works. I don't change the proxy command configuration on the ssh config. Maybe It was something machine related, but I was connecting directly from terminal and it was working.

Well, for now I can assume that "it was a wizard".

Thanks for your help!

**Comment by marksantcroos** [comment]
Happy to hear its working now! And thanks for bringing it up and reporting the success.
