### ISSUE TITLE
Error when trying to instantiate a Large Instance using SAGA

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#493]
I receive the following error when running [dynamic_ec2_pilot](https://github.com/radical-cybertools/radical.pilot/blob/fix/attribs/examples/misc/dynamic_ec2_pilot.py) after I change the variable `cd.template = 'Large Instance'`. I changed this variable intending to launch a c3.2xlarge instance rather than a small instance. Is there a way to change certain values to control which instance types will be instantiated?

Below is the error I received. Please don't mind the change in the name of the file. That was simply to make the naming easier for the CCT folks.

RP Version : v0.37.10-379-g200cbc6@fix-attribs
SAGA Version: v0.39-42-g5cfb4f2@devel

```
Traceback (most recent call last):
  File "dynamic_ec2_pilot_HiComb.py", line 301, in <module>
    main()
  File "dynamic_ec2_pilot_HiComb.py", line 52, in main
    cr     = start_cr()
  File "dynamic_ec2_pilot_HiComb.py", line 140, in start_cr
    cr = rm.acquire(cd)
  File "/home/mingtaiha/ve/ve.HiComb/local/lib/python2.7/site-packages/saga/resource/manager.py", line 251, in acquire
    return self._adaptor.acquire (spec, ttype=ttype)
  File "/home/mingtaiha/ve/ve.HiComb/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtaiha/ve/ve.HiComb/local/lib/python2.7/site-packages/saga/adaptors/aws/ec2_resource.py", line 724, in acquire
    raise saga.NoSuccess ("Failed with %s" % e)
saga.exceptions.NoSuccess: Failed with VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (/home/mingtaiha/ve/ve.HiComb/local/lib/python2.7/site-packages/saga/adaptors/aws/ec2_resource.py +724 (acquire)  :  raise saga.NoSuccess ("Failed with %s" % e))
```

**Comment by andre-merzky** [comment]
Ah,  right, SAGA does not support Amazon's 'Virtual Private Cloud' (VPC).  Do you actually want to create/use a VPC?  If not, you will have to use a different (non-VPC) instance type.  If you do, and if this is a hard requirement for your users, then we would need to look into VPC support.  But I would hesitant to go that route, as it looks that real VPC support can become complex rather quickly, and I don't consider infrastructure management to be a target domain for SAGA, really...

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html

Best, Andre.

**Comment by mingtaiha** [comment]
Their current use-case is for C3 instances (namely c3.2x), and that instance type can be launched using EC2-Classic. How would I able to launch a non-VPC instance type?.

In any case, I will ask them again, and look into the types of instances that they want to use and any reasons they have for using VPC.

Thanks for the help, Ming

**Comment by andre-merzky** [comment]
This page:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html#vpc-only-instance-types
lists the instance types which are only usable in a VPC.  You should be able to use any other instance type in SAGA (I think).

**Comment by mingtaiha** [comment]
I see. Would I have to specify a different image in order to use a non-VPC version, while `template = 'Large Instance'`?

**Comment by andre-merzky** [comment]
Not all images  work  with all instances, and vice versa.  SAGA does not perform any  sanity check (nor would I know how to do that, really).  The main thing you have to check is that the architecture of instance and image are matching.  If you make your instance just larger (changing number of cores w/o changing processor type, etc), then the same image should be usable in general...

HtH, Andre.

**Comment by andre-merzky** [comment]
I am closing this ticket for now - please let me know if that continues to be a problem for your application!
