### ISSUE TITLE
support environment variables in session parameter file paths

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#494]
At present it seems that file paths passed to session parameters cannot include environment variables, e.g. the ability to specify a filename including $HOME.

For example, the following results in an error even though $HOME/.ssh/my_user_key is a valid key file:

```
import saga

ctx = saga.Context("ssh")
ctx.user_id='myuser'
ctx.user_key='${HOME}/.ssh/my_user_key'
s = saga.Session(default=False)
s.add_context(ctx)
```

This gives an exception similar to the following:

```
BadParameter: Cannot add context, initialization failed (ssh key inaccessible: ${HOME}/.ssh/my_user_key …
```

This would be a useful addition.

**Comment by jcohen02** [comment]
Just to update the previous post, I note that in the Session class, the [documentation](https://github.com/radical-cybertools/saga-python/blob/5cfb4f23aa922ff8047ef005f29bc5bf4757621d/src/saga/session.py#L180-L195) suggests that $HOME can be used paths for certificate and key files so it looks like there may be a bug here?

It also looks like there are some errors in the [example](https://github.com/radical-cybertools/saga-python/blob/5cfb4f23aa922ff8047ef005f29bc5bf4757621d/src/saga/session.py#L180-L195) too - at least with the current version of the API - the creation of a Context appears to require a parameter - `c = saga.Context()` throws an error - and I assume the parentheses are missing from `s = saga.Session`. Also, should the file paths for `c.user_cert` and `c.user_key` be switched round?

**Comment by andre-merzky** [comment]
Thanks for thePR, Jeremy!  I also fixed the docs as suggested, that will be merged soon I assume.
