### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by mehdisadeghi** [radical-cybertools/saga-python#498]
For us #480 was a blocking issue, therefore I suggest to have a new release or set a milestone for it.

BTW, I didn't know where to bring up this request, so I opened an issue for it. Feel free to close it if this is not the right place for this.

Thanks.

**Comment by andre-merzky** [comment]
An issue is the right thing to do, thanks.

Mark, could you please look over the open pull requests, to give a yay or nay for merge before release?  Thanks!
