### ISSUE TITLE
State callbacks not being made in PBS job adapter

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#500]
I'm experiencing issues when running jobs via the PBSJobService where a registered state callback function is not being called when expected.

I execute a job using the following approach:

```
jd = saga.job.Description()

### Set up job description parameters…

job = self.service.create_job(jd)
job.add_callback(saga.job.STATE, state_cb)

job.run()
job.wait()
```

I see one call of the callback function very soon after the job has been started where the state is set to `Pending` and the job ID value has been populated. After this I see no further calls to the callback function.

Debug output shows that the job monitoring thread is running. However, adding some additional debug output to the [job_state_monitor function](https://github.com/radical-cybertools/saga-python/blob/9f9b8edf8c0e488a3e6a87c95f52de4c5641cd11/src/saga/adaptors/pbs/pbsjob.py#L35-L102) in the [pbsjob.py](https://github.com/radical-cybertools/saga-python/blob/9f9b8edf8c0e488a3e6a87c95f52de4c5641cd11/src/saga/adaptors/pbs/pbsjob.py) module shows that the existing value for the job state `job_info['state']` is always the same as the new value `new_job_info['state']` which is obtained from the job service `new_job_info = self.js._job_get_info(job_id, reconnect=False)`.

Not sure if I'm doing something wrong in the way I'm configuring my jobs or setting up the callback but it looks like the job information in `jobs[job_id]` is being updated externally since it always contains the latest job status. As a test, removing the if statement `if  new_job_info['state'] != job_info['state']:` [here](https://github.com/radical-cybertools/saga-python/blob/9f9b8edf8c0e488a3e6a87c95f52de4c5641cd11/src/saga/adaptors/pbs/pbsjob.py#L78) causes the callback to be called on every iteration of the job monitor and changes in the state can be seen correctly.

**Comment by jcohen02** [comment]
It looks like this issue is a result of [this](https://github.com/radical-cybertools/saga-python/blob/9f9b8edf8c0e488a3e6a87c95f52de4c5641cd11/src/saga/adaptors/pbs/pbsjob.py#L73-L80) code:

```
new_job_info = self.js._job_get_info(job_id, reconnect=False)
self.logger.info ("Job monitoring thread updating Job %s (state: %s)" \
                          % (job_id, new_job_info['state']))

# fire job state callback if 'state' has changed
if  new_job_info['state'] != job_info['state']:
    job_obj = job_info['obj']
    job_obj._attributes_i_set('state', new_job_info['state'], job_obj._UP, True)
```

Since job_info appears to hold a reference to an item in the `jobs` dictionary which is obtained from the job service, and  the implementation of the job service function `_job_get_info` updates that dictionary, I'm assuming that the call to `_job_get_info` is updating the value of `job_info['state']` and the returned `new_job_info` is actually a reference to the same object as `job_info`. As a result, the check `if  new_job_info['state'] != job_info['state']:` will always be false.

As a quick test, storing `job_info['state']` to a local `pre_update_state` variable in the monitor and then subsequently comparing `new_job_info['state']` with `pre_update_state` resolves the issue and results in the callback function being correctly called when the status changes.

**Comment by andre-merzky** [comment]
Hi Jeremy, 

Thanks for digging into this issue!  It is surprising that we did not stumble over that before :/   I agree on the quick fix you proposed -- would you be willing to provide a pull request?  I guess the same would apply to the torque adaptor?

Thanks, Andre.

**Comment by jcohen02** [comment]
I've made the fix for this issue to the PBS adaptor and also to the PBSPro and Torque adaptors.

I've tested the fix on the PBS adaptor but don't have a suitable environment to test with the Torque adaptor. Given the nature of the issue and the fact that the state monitoring code in the Torque adapter seems to be the same, I'm assuming this will work but it would be great if someone could test it.

**Comment by andre-merzky** [comment]
This is considered fixed.
