### ISSUE TITLE
Incorrect option used on LSF for job_contact

### ISSUE THREAD

**Issue by jvegasbsc** [radical-cybertools/saga-python#501]
On the LSF adapator you are using -U option for job_contact. This is used to specify a reservation ID.

```
if jd.job_contact is not None:
        lsf_params += "#BSUB -U %s \n" % str(jd.job_contact)
```

To provide the user email is the option -u. Check this link:
http://www.ccs.miami.edu/hpc/lsf/9.1.1/lsf_command_ref/index.htm?bsub.1.html~main

Thanks,
Javi

**Comment by marksantcroos** [comment]
Hi Javi, you are right, good catch. Will fix!
