### ISSUE TITLE
Allow saga.job.Description to be inherited

### ISSUE THREAD

**Issue by jvegasbsc** [radical-cybertools/saga-python#502]
I am using a class that inherits from saga.job.Description to add a new attribute ('Reservation') for a custom adaptor I am working on.  I have just modified the constructor and override the clone just to create an instance of this new class.

```python
def __init__(self):
        super(Description, self).__init__()
        self._attributes_register('Reservation', None, saga.attributes.STRING, saga.attributes.SCALAR, saga.attributes.WRITEABLE)
```

This approach does not work because of two problems with the Service.create_job() method:

First, you are cloning the job description without using the clone method:
```python
 jd_copy = descr.Description()
 job_desc._attributes_deep_copy (jd_copy)
```
This new Description is always the base class and not the one I am providing, so it does not have the reservation attribute registered and fails.

I think you can substitute it for:
```python
 jd_copy =  job_desc.clone()
```

Second, you are creating a new description object to get the default values:
```python
# use an empty job description to compare default values
 jd_default = descr.Description ()
```

This object does not have the 'Reservation' attribute I added so it is launching an exception when trying to retrieve it. I think this can be solved creating the default using the same class of the given object:

```python
# use an empty job description to compare default values
jd_default = jd_copy.__class__()
```

I have made this changes on my local installation and now it's working fine. 

Thanks, 
Javi

PS: This is the way I have found to overcome the limitation of not being able to add attributes to the job.Description class. If you don't like it for any reason, please provide a way to allow users to define new attributes because they can be needed for custom adaptors.

**Comment by marksantcroos** [comment]
I'll let the issue of inheritance to Andre, but will answer on the specific problem you try to solve.

We recently had a similar situation of using a reservation, and instead of deviating from the SAGA specification we decided to use the `project` attribute for that.
You can find the specific commit here 24c1164. The semantics is that if there is a colon in the attribute, then the second part is the reservation string.

Would that approach work for you?

**Comment by andre-merzky** [comment]
Hi Javi, 

I have two levels of comment - technical and non-technical.  The easy one first :)

Technically, all points raised wrt. inheritance make sense I think, and we should fix those.  Related though, we should probably try to get `copy.deepcopy()` supported.  The reason why the `_attributes_deep_copy` method exists is that back then I could not get `deepcopy` support working :/  Getting that fixed would simplify things (also in other places of SAGA-Python).   I certainly agree with the use of `jd_copy.__class__()` for construction - that looks neat, at least for empty / non-overloaded `__init__` signatures.

On a non-technical level, I am rather hesitant to embrace the extension of the SAGA API  via inheritance, at least for the specific use case you mention: adding adaptors.  Going that route would break the main premise of SAGA, that the same code works, at least in principle, towards different backends.  The overarching design principle of SAGA is to:

```
Provide an simple API that can be used with much less effort compared to
the vanilla interfaces of existing grid middleware. A guiding principle for
achieving this simplicity is the 80–20 rule: serve 80 % of the use cases with
20 % of the effort needed for serving 100 % of all possible requirements.
````
(see https://www.ogf.org/documents/GFD.90.pdf, sec. 1.1)

It is certainly true that the   goal of portability limits the usability of SAGA to some extent, in that it will not be able to serve specific use cases, but that is indeed a conscious trade-off which we have accepted so far (albeit often grudgingly).

Having said that, I would propose to reconsider the comment made by Mark, to encode the reservation as part of the `Project` identifier.  This is not really nice either, but is somewhat more true to the gist of SAGA, in that it leaves the API unchanged.  I would also like to add that we collected quite a number of things over time which should make it into a revised API at some point (and also a number of things which should get thrown out of the API, really).  `Reservation` is certainly one of the things which eventually make it into the API.

HtH, Andre.

**Comment by jvegasbsc** [comment]
First of all, thanks for your help and clarifications.

I will use the approach suggested by Mark. If you are using it on other adaptors, it makes total sense that I'll use it on mine for compatibility.

On behalf of the adding attributes support part, I did not know anything about the SAGA standard definition, so I didn't know if this suggestion made sense at all. 

Thanks for your help
