### ISSUE TITLE
SSH context initialisation fails for encrypted key passwords containing spaces

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#509]
Not sure if this is a bug or just a shell-specific or platform-specific issue (Mac OS X) but it looks like ssh context initialisation fails when using an encrypted key that has a password containing spaces. This appears to be a result of the way the `subprocess.call` call is set up [here](https://github.com/jcohen02/saga-python/blob/9947658c1ec9568e073f432be8bff219d1012c57/src/saga/adaptors/context/ssh.py#L284)

To reproduce the error, try something like the following:

```
ssh-keygen -b 2048 -f mytestkey
```

When prompted for a password enter `my password`.  Now try and create an SSH context using this key:

```
import saga

s = saga.Session(default=False)
ctx = saga.Context("ssh")
ctx.user_id = 'testuser'
ctx.user_key = '/full/path/to/mytestkey'
ctx.user_pass = 'my password'

s.add_context(ctx)
```

This results in an error, the end of the stack trace showing:

```
/.../saga/session.pyc in _initialise_context(self, ctx, session)
     90             except se.SagaException as e :
     91                 msg = "Cannot add context, initialization failed (%s)"  %  str(e)
---> 92                 raise se.BadParameter (msg)
     93 
     94         return ctx_clone

BadParameter: Cannot add context, initialization failed (ssh key '/.../mytestkey' is encrypted, incorrect password (/.../saga/adaptors/context/ssh.py +294 (_initialize)  :  raise se.PermissionDenied ("ssh key '%s' is encrypted, incorrect password" % (key)))) (.../saga/session.py +92 (_initialise_context)  :  raise se.BadParameter (msg))
```

Prior to this, the help output for ssh-keygen appears which seems to suggest that it is being called with invalid parameters.

Recreating the command run by [this line](https://github.com/jcohen02/saga-python/blob/9947658c1ec9568e073f432be8bff219d1012c57/src/saga/adaptors/context/ssh.py#L284) on the terminal suggests that the password needs escaping:

```
sh -c 'ssh-keygen -y -f mytestkey -P my password'
```

Displays the `ssh-keygen` help.

```
sh -c 'ssh-keygen -y -f mytestkey -P my\ password'
```

Results in the command running correctly.

**Comment by andre-merzky** [comment]
Indeed, you are right on target: escaping or quoting is missing here!  Thanks for spotting that and tracking it down!

**Comment by vivek-bala** [comment]
PR #510 fixes this issue.
