### ISSUE TITLE
Exceptions when running simultaneous saga scripts

### ISSUE THREAD

**Issue by millingw** [radical-cybertools/saga-python#513]
I have a simple task executed inside celery, based on the saga tutorial examples. Running a single task works, up to the fourth task. When I try to run more tasks, the tasks fail with the following error:

```
[2016-02-01 13:11:36,048: WARNING/Worker-1] An exception occured: (NoSuccess) Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (Shared connection to indy0.epcc.ed.ac.uk closed.
) ((Shared connection to indy0.epcc.ed.ac.uk closed.
)) (/disk/fortissimo-dev0/home/millingw/celery_test/venv/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg))
```

Reading other issues, I wonder if this is a bug in the handling of the shared ssh connection? I've got OpenSSH_5.3p1 on the client, OpenSSH_5.1p1 on the execution host.

**Comment by andre-merzky** [comment]
Are you creating a new SAGA session and a new job service for each celery task?  If so, you may simply be hitting a limit of concurrent ssh connections.  The sshd configuration on the target host is likely configured for a max of shared and non-shared connections.  The actual max numbers cannot really be inspected from the outside, but when that number is exceeded, connections will drop.

If that is not the issue, you may indeed run in a SAGA layer problem, in the sense that we screw up with the channel management over different threads.  In that case I would appreciate a log file with `export SAGA_VERBOSE=DEBUG`.  What version are you running, and what OS are client and target host?

Thanks, Andre.

**Comment by millingw** [comment]
Hi Andre, to confirm, I am creating a new session and service each time. I'll try and change my code to cache the session and job service, and report back on outcome. For the record, the client is Scientifc Linux, the target host is SUSE Linux, SAGA is version 0.39

**Comment by millingw** [comment]
It appears that celery runs each task as a separate process, so there does unfortunately not appear to be a way to cache the session and service between tasks. To try and make debugging easier, I've extracted the task code to a seperate script, and run this once celery started failing. Attached is the output from the script
[log-debug.txt](https://github.com/radical-cybertools/saga-python/files/112463/log-debug.txt)

, with debug mode set.

**Comment by andre-merzky** [comment]
Hmm, sharing session and job service over processes is indeed not possible, so the reuse mechanism for ssh client channels won't kick in.  I don't have an immediate answer to that problem -- that really is more an ssh configuration problem than SAGA limitation...

Would you mind giving more details of your use case?  Do the celery tasks perform much other work besides the SAGA job spawning?  If not, what was the motivation to  use celery tasks?  Was SAGA job spawning to slow?  If they do lots of other work: would it be possible to centralize the job spawning part, and have the celery worker tasks request jobs to be spawned from a central agent?

**Comment by millingw** [comment]
We're trying to convert an existing django web application to use a batch scheduler back end. The web app is intended to launch lots of independent single-core python jobs to do simulation on a set of input parameters, either running on the web host or on the remote host according to user preference. We want to use celery so that we can manage all the jobs in one place, regardless of whether they are executing locally or remotely, by placing appropriate tasks in the celery queue. In terms of the SAGA tasks, we just need to be able to stage an input file, kick off a job and wait for it, retrieve an output file then delete the job's working directory.

One thing that puzzles me is that I get exceptions after executing exactly 4 tasks in the celery queue - seems to be completely reproducible.

I'll try and get hold of another machine such as an AWS instance to test with a newer version of ssh.

**Comment by andre-merzky** [comment]
Thanks for the details!

> I'll try and get hold of another machine such as an AWS instance to test with a newer version of ssh.

This is likely a server side limitation though.  You might be able to reproduce it on command line, by creating multiple master and client ssh connections to your target host.

Would you mind sharing a skeleton of your celery code?  I should read up on celery to understand what options we would have to get this working.  I am glad you seem to find SAGA appropriate for the task in general, so we are very interested to get that use case working.  Also, you are not the first one asking for integration with celery, so getting this solved may also help other users...

Thanks for bearing with us, 

Andre.

**Comment by millingw** [comment]
Just had a chat with one of our admins. It could be that I'm hitting an ssh rate limit, as opposed to an actual limit on number of connections - if I'm opening too many new connections in a short period of time, then this might be categorized as an attempted brute force attack and further connections from the same host are blocked for a period of time. I think your agent idea using the same ssh connection is something we need to look into.

The following is my celery test task. It really is just a very slight modification of the example in the tutorial

import sys
import saga
from celery import Celery

app = Celery('tasks', broker='amqp://guest@localhost//')

@app.task(bind=True)
def run_example(self):

    try:


        ctx = saga.Context("SSH")
        ctx.user_id = ***
        ctx.user_cert = ***
        ctx.user_key = ***
        ctx.user_pass = ***

        session = saga.Session()
        session.add_context(ctx)

        # Create a job service object that represent the local machine.
        # The keyword 'fork://' in the url scheme triggers the 'shell' adaptor
        # which can execute jobs on the local machine as well as on a remote
        # machine via "ssh://hostname".
        js = saga.job.Service(***, session=session)

        # describe our job
        jd = saga.job.Description()


         # Next, we describe the job we want to run. A complete set of job
        # description attributes can be found in the API documentation.
        jd.executable      = '../run_task.sh'
        jd.output          = "mysagajob.stdout"
        jd.error           = "mysagajob.stderr"

        # get the unique celery id
        celery_id = self.request.id

        # use this to create and set a working directory for the remote job
        remote_working_dir = '/home/w02/millingw/example/tests/' + celery_id
        jd.working_directory = remote_working_dir

        # Create a new job from the job description. The initial state of
        # the job is 'New'.
        myjob = js.create_job(jd)

        # Check our job's id and state
        print "Job ID    : %s" % (myjob.id)
        print "Job State : %s" % (myjob.state)

        print "\n...starting job...\n"

        # Now we can start our job.
        myjob.run()

        print "Job ID    : %s" % (myjob.id)
        print "Job State : %s" % (myjob.state)


        print "\n...waiting for job...\n"
        # wait for the job to either finish or fail
        myjob.wait()

        print "Job State : %s" % (myjob.state)
        print "Exitcode  : %s" % (myjob.exit_code)

        js.close()


        print "completed"

        return 0

    except saga.SagaException, ex:
        # Catch all saga exceptions
        print "An exception occured: (%s) %s " % (ex.type, (str(ex)))
        # Trace back the exception. That can be helpful for debugging.
        print " \n*** Backtrace:\n %s" % ex.traceback
        return -1

**Comment by andre-merzky** [comment]
Thanks for the followup and code!  I'll probably need a couple of days until I can dig into it test wise though, apologies :/  Some deadlines are breathing down my neck...

**Comment by millingw** [comment]
It turns out celery *does* gives us the ability to create and cache objects at the worker level. I've been able to create a single job service instance inside a worker, then have each task use this instead of creating its own. This seems to get us round the rate limit. However, if I want to do file transfer as well, each transfer appears to be using its own connection. Can you think of a way round this? I've tried creating a global session and using this, but it doesnt seem to get round the problem.

session = None
js = None
@worker_process_init.connect
def init_worker(**kwargs):
    print('Initializing worker.')
    ctx = saga.Context("SSH")
    ctx.user_id = ***
    ctx.user_cert = ***
    ctx.user_key = ***
    ctx.user_pass = ***

    global session
    session = saga.Session()
    session.add_context(ctx)

    # Create a job service object that represent the local machine.
    # The keyword 'fork://' in the url scheme triggers the 'shell' adaptor
    # which can execute jobs on the local machine as well as on a remote
    # machine via "ssh://hostname".
    global js
    js = saga.job.Service(***, session=session)

def run_example(self):
...
  outfilesource = 'sftp://...'
  outfiletarget = 'file://localhost/...'
  global session
  out = saga.filesystem.File(outfilesource, session=session)
  out.copy(outfiletarget)

**Comment by andre-merzky** [comment]
Yes, indeed, the shell adaptor keeps a private connection handle for some FS actions.  Let me check if those can simply be converted to shared ones.  I think the motivation was state management: the dir object in SAGA has a PWD, and any shell activity is scoped by that PWD.  Sharing a single remote shell over multiple object instances needs to reset the PWD before every operation...

**Comment by andre-merzky** [comment]
Could you please give the `feature/shared_shell_for_files` branch a try?  It should now use a shared channel in all places...

**Comment by millingw** [comment]
After some internal discussion, we've decided not to use celery after all (but we are still going to use saga-python!). Its likely that our application will lie dormant for long periods of time, followed by short bursts of activity. Whilst we could use a shared job service in the worker as above, detecting and managing ssh timeouts after long periods of inactivity is likely to be difficult to test reliably. Instead we're going to try implementing our own simple task manager (using saga-python) which should give us much more control over the lifetime of the job service and file instances.

**Comment by millingw** [comment]
We have proceeded with our own task manager. I've now come up against a couple of things. When the code runs, it creates a remote directory for each new task. Is there an easy way to check if the directory already exists? I've tried using dir.exists, but this seems to throw a NotImplemented exception. Secondly, I'd like to be able to delete the remote directory and all of its files after the task has finished, but dir.remove throws an exception if I give it a directory. Is there an easy way to delete a remote directory?

**Comment by andre-merzky** [comment]
Hi @millingw, 

I consider both items (`dir.exists` and `dir.remove`) to be bugs, we should fix them.  You are using the right methods :)  I'll open separate  tickets for them.  Thanks!

**Comment by jcohen02** [comment]
Hi @millingw, I also encountered the issue of `dir.exists` throwing a `NotImplemented` exception, however, `dir.is_dir` and `dir.is_file` both seem to work so could be used as possible alternatives to `dir.exists`.

**Comment by andre-merzky** [comment]
Hi @millingw -- can this  ticket be closed in favor of the separate tickets on `dir.remove` and `dir.exists`?

**Comment by millingw** [comment]
Yes, that would make sense. I'll close the ticket.
