### ISSUE TITLE
Documentation - missing return statement in callback example

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#522]
The callback example shown in the [Metrics](https://github.com/radical-cybertools/saga-python/blob/devel/docs/source/library/job/index.rst#metrics) documentation does not include a return statement:

```python
# create a callback function
def state_cb (self, source, metric, value) :
  print "Job %s state changed to %s : %s"  % (source, value)
```

I was having issues with my callback function only being called once. After investigating I see that in [line 492](https://github.com/radical-cybertools/saga-python/blob/fcdc22247cb050dad63305744e02b2934a8369f0/src/saga/attributes.py#L491-L492) of `attributes.py` it appears that a callback is removed `if not ret`. Since `ret` is `None` if there is no return statement at the end of the function, the callback is removed after its first call. This should be highlighted in the documentation.

**Comment by andre-merzky** [comment]
Hi Jeremy, 

this is documented here: http://saga-python.readthedocs.org/en/latest/library/attribute.html  I'll make sure that this is highlighted.  Do you have any  suggestion where else a note would be useful?  For example, where / in what example did you miss the documentation specifically?  Thanks!

**Comment by jcohen02** [comment]
Hi Andre,

I was looking at the example in the job submission and control documentation page, in the Metrics section, [http://saga-python.readthedocs.org/en/latest/library/job/index.html#metrics](http://saga-python.readthedocs.org/en/latest/library/job/index.html#metrics).

This is my mistake for not looking in more detail at the specifics in the `add_callback` section, however, the text above the example says "The registered callback functions are triggered whenever a job metric changes.". Maybe adding an explicit return value to the example with a comment, or just a note saying that "...the return value of a callback function determines whether or not it remains registered after it is run." might clarify things further? Thanks. Jeremy.

**Comment by andre-merzky** [comment]
thank you for pointing that out -- I'll make that more specific, and/or add a cross-reference!

**Comment by andre-merzky** [comment]
This is fixed in a pull request, and will make it into the next release.  Thanks again!
