### ISSUE TITLE
PTYShell read_from_remote attempts to read from a closed file handle

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#530]
Two file handles are used in [read_from_remote](https://github.com/radical-cybertools/saga-python/blob/0e20b559f334e0bc78497393582666bedcb216e8/src/saga/utils/pty_shell.py#L837), one to read the requested file from the remote resource to a local temporary file and then a second to read data from temporary file to return it to the caller.

Calling this function currently throws an exception:

```Python
AttributeError: 'int' object has no attribute 'read'
```
It looks like `fhandle` on [line 860](https://github.com/radical-cybertools/saga-python/blob/0e20b559f334e0bc78497393582666bedcb216e8/src/saga/utils/pty_shell.py#L860) should actually be `fhandle2`!

**Comment by andre-merzky** [comment]
Yes, that PR looks right on target :)
