### ISSUE TITLE
Stampede, exitcode -1 

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/saga-python#552]
slurm.py fails on Stampede I can't find the error log though. I noticed the url of working directory doesn't exist so I changed the working directory from  $SCRATCH/A/B/C"  to jd.working_directory = "A/B/C"   and it worked.

`2016-05-12 17:15:06,330: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [  192]   ($SCRATCH/A/B/C\n   StdErr=/home1/03662/tg829618/$SCRATCH/A/B/C/examplejob.err\n   StdIn=/dev/null\n   StdOut=/home1/03662/tg829618/$SCRATCH/A/B/C/examplejob.out\n   Power= SICP=0\n\nPROMPT-0->)`

**Comment by andre-merzky** [comment]
George, is this still relevant?

**Comment by georgeha** [comment]
No, I run the example and it is fine.
