### ISSUE TITLE
Shell adaptor crash

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/saga-python#553]
Hello,

Recently i got a problem with shell adaptor. It started crashes on user cluster at CERN (lxplus.cern.ch)
Here is backtrace, which i got: 
```
--------------------------------------------------
python
Python 2.7.9 (default, Mar 17 2015, 11:45:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import saga
saga.version
  '0.40.1'
ctx = saga.Context("UserPass")
ctx.user_id = "login"
ctx.user_pass = "password"
session = saga.Session()
session.add_context(ctx)
js = saga.job.Service("ssh://lxplus.cern.ch", session=session)
2016-05-13 19:55:22,692: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : host bootstrap failed - no pid (PID: 18511
mkfifo: cannot create fifo `/afs/cern.ch/user/d/doleynik/.saga/adaptors/shell_job//fifo': Operation not permitted
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "saga/adaptors/shell/shell_job.py", line 507, in init_instance
    self.initialize ()
  File "saga/adaptors/shell/shell_job.py", line 591, in initialize
    raise saga.NoSuccess ("host bootstrap failed - no pid (%s)" % out)
saga.exceptions.NoSuccess: host bootstrap failed - no pid (PID: 18511
mkfifo: cannot create fifo `/afs/cern.ch/user/d/doleynik/.saga/adaptors/shell_job//fifo': Operation not permitted
) (saga/adaptors/shell/shell_job.py +591 (initialize)  :  raise saga.NoSuccess ("host bootstrap failed - no pid (%s)" % out)) 
---------------------------------------------------
```

Looks like that problem caused "mkfifo"  command. After short googling, i found that 'mkfifo' not supported by AFS, unfortunately user home directories at CERN cluster placed on AFS (i don't know why this issue appeared only now). 
I use shell adaptor in one small, but very important utility to support PanDA production on Titan, so it's a kind of critical for me (and ATLAS collaboration :-) ).
 
Best regards,
Danila Oleynik, PanDA project

**Comment by andre-merzky** [comment]
Hi Danila, 

yeah, an FS not supporting a FIFO will screw things up.  Do you have the option to use a different FS, such as `/tmp/`?  If so, I can make the location of the fifo (or rather the job service workdir which contains the fifo) configurable.  

FWIW, the only way I can think of where that would make things worse is, for example, if you connect to a cluster with multiple, randomly selected login nodes -- any secondary job service instance landing on a different headnode could not reconnect to jobs from other job service instances.

**Comment by DanilaOleynik** [comment]
Hi Andre,

Yes, there is local FS (/tmp/) on each node of lxplus. 

In my case i do not expect problems with connection with job from secondary job service (for the moment  i have no such option in workflow for this utility).  

Thank you,
Danila

**Comment by andre-merzky** [comment]
Daniele, 

would you please try the following:

  * in `$HOME/.saga.cfg` (on localhost), add:

  ```
  [saga.adaptor.shell_job]
  base_workdir = /tmp/saga_tmp/
  ```

  * use the `feature/shell_basedir` branch

This should result in the data (and the fifo) being stored in `/tmp/saga_tmp` on the target host.  Please let me know if that works.

Thanks, Andre.

**Comment by DanilaOleynik** [comment]
Hi Andre,

Thank you for fix! It works well.
Unfortunately i got another problem, when i try to download file through SFTP.
-----------------------------------------
import saga
ctx = saga.Context("UserPass")
ctx.user_id = "username"
ctx.user_pass = "password"
session = saga.Session()
session.add_context(ctx)
outfilesource = 'sftp://lxplus.cern.ch/afs/cern.ch/user/d/doleynik/proxy/x509up_u5591'
outfiletarget = 'sftp://localhost/Users/doleynik/Development/tmp/'
out = saga.filesystem.File(outfilesource, session=session)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "saga/adaptors/shell/shell_file.py", line 1054, in init_instance
    self.initialize ()
  File "saga/adaptors/shell/shell_file.py", line 1095, in initialize
    ret, out, _ = self._run_sync(cmd)
  File "saga/adaptors/shell/shell_file.py", line 989, in _run_sync
    return shell.obj.run_sync("cd %s && %s\n" % (cwd_path, cmd))
AttributeError: 'PTYShell' object has no attribute 'obj'

----------------------------

Should i open another track for this? 

Cheers,
Danila

**Comment by andre-merzky** [comment]
Thanks for the feedback!  I'll be closing this ticket in favor of #554 then.
