### ISSUE TITLE
SFTP with shell adaptor crashes

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/saga-python#554]
Hello, 

I got crash with SFTP file transfer from remote host. (saga version 0.41.RC1)  

```
import saga
ctx = saga.Context("UserPass")
ctx.user_id = "username"
ctx.user_pass = "password"
session = saga.Session()
session.add_context(ctx)
js = saga.job.Service("ssh://lxplus.cern.ch", session=session)
outfilesource = 'sftp://lxplus.cern.ch/afs/cern.ch/user/d/doleynik/job_results'
outfiletarget = 'sftp://localhost/Users/doleynik/Development/tmp/'
out = saga.filesystem.File(outfilesource, session=session)
Traceback (most recent call last):
File "", line 1, in 
File "saga/filesystem/file.py", line 86, in init
adaptor, adaptor_state, _ttype=_ttype)
File "saga/namespace/entry.py", line 89, in __init
url, flags, session, ttype=ttype)
File "saga/base.py", line 101, in __init_
self._init_task = self._adaptor.init_instance (adaptor_state, args, *kwargs)
File "saga/adaptors/cpi/decorators.py", line 57, in wrap_function
return sync_function (self, args, *kwargs)
File "saga/adaptors/shell/shell_file.py", line 1054, in init_instance
self.initialize ()
File "saga/adaptors/shell/shell_file.py", line 1095, in initialize
ret, out, _ = self._run_sync(cmd)
File "saga/adaptors/shell/shell_file.py", line 989, in _run_sync
return shell.obj.run_sync("cd %s && %s\n" % (cwd_path, cmd))
AttributeError: 'PTYShell' object has no attribute 'obj'
```

**Comment by andre-merzky** [comment]
Hi Danila, 

Could you please give branch `fix/554` a try?

Many thanks, 

  Andre.

**Comment by DanilaOleynik** [comment]
Hi Andre,

I am a bit busy today with OLCF meeting, sorry for delay with answer. 

Unfortunately I got next bug: 

>>> import saga
>>> ctx = saga.Context("UserPass")
>>> ctx.user_id = "user"
>>> ctx.user_pass = "pass"
>>> session = saga.Session()
>>> session.add_context(ctx)
>>> js = saga.job.Service("ssh://lxplus.cern.ch", session=session)
>>> outfilesource = ‘sftp://lxplus.cern.ch/afs/cern.ch/user/d/doleynik/some.file'
>>> outfiletarget = 'file://localhost/Users/doleynik/Development/tmp/'
>>> out = saga.filesystem.File(outfilesource, session=session)
>>> out.copy(outfiletarget)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "saga/namespace/entry.py", line 266, in copy
    return self._adaptor.copy_self (tgt, flags, ttype=ttype) 
  File "saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "saga/adaptors/shell/shell_file.py", line 1202, in copy_self
    files_copied = self._stage_from_remote (src.path, tgt.path, rec_flag)
AttributeError: 'ShellFile' object has no attribute '_stage_from_remote'
>>> 

Looks like that ._self_from_remote() was some how redefined. 

Cheers,
Danila

**Comment by andre-merzky** [comment]
Danila -- we have been able to reproduce this problem now.  Can you please try the `fix/554` branch once again, it should now have the fix.

Thanks, Andre.

**Comment by DanilaOleynik** [comment]
Hi Andre,

I works well now! 
Thank you very much!

Cheers,
Danila

**Comment by andre-merzky** [comment]
thanks for the confirmation, this will go into the next release then.

Best, Andre.
