### ISSUE TITLE
slurm: incomplete info for completed jobs

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#562]
From Mark Perri:

I can call job.get_state() which returns Done correctly.  Is there any way to get the run time and number of cores that were used from that job?  If I try:

```
job=jsComet.get_job("[slurm+ssh://comet.sdsc.edu]-[3183494]")
print job.get_state()
jd = job.get_description()
print jd.processes_per_host
print jd.total_cpu_count
```

I get:

```
Done
None 
None
```

**Comment by vivek-bala** [comment]
Similar to #180 . Will be fixed in version 2.
