### ISSUE TITLE
Improvements with method `_pbscript_generator()`

### ISSUE THREAD

**Issue by wjlei1990** [radical-cybertools/saga-python#564]
Hi,

I found there is improvements could be made in `adaptors/pbs/pbsjob.py`. In the function of `_pbsscript_generator()`, line https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/pbs/pbsjob.py#L319:

``` python
    # escape all double quotes and dollarsigns, otherwise 'echo |'
    # further down won't work
    # only escape '$' in args and exe. not in the params
    exec_n_args = workdir_directives + exec_n_args
    exec_n_args = exec_n_args.replace('$', '\\$')

    pbscript = "\n#!/bin/bash \n%s%s" % (pbs_params, exec_n_args)
    pbscript = pbscript.replace('"', '\\"')
```

The replacement of `$` is not good if you want to put some bash variable inside your pbs script...but you can't do that because `$` will be translated to `\$`.

The reason "$" needs to be replaced is because of line https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/pbs/pbsjob.py#L693:

``` python
        cmdline = """SCRIPTFILE=`mktemp -t SAGA-Python-PBSJobScript.XXXXXX` &&  echo "%s" > $SCRIPTFILE && %s $SCRIPTFILE && rm -f $SCRIPTFILE""" %  (script, self._commands['qsub']['path'])
        ret, out, _ = self.shell.run_sync(cmdline)
```

However, this issue could solved if change the `echo "%s" > $SCRIPTFILE` to `echo '%s' > $SCRIPTFILE`. Thus, the echo just dump the string content in a verbose way without interpolation. Accordingly, the escape rule should be changed to:

``` python
    # escape all single quotes, otherwise 'echo |'
    # further down won't work
    # only escape  in args and exe. not in the params
    exec_n_args = workdir_directives + exec_n_args

    pbscript = "\n#!/bin/bash \n%s%s" % (pbs_params, exec_n_args)
    exec_n_args = exec_n_args.replace('\'', '\\\'')
```

I have created a pull request: https://github.com/radical-cybertools/saga-python/pull/566

**Comment by wjlei1990** [comment]
However, at runtime, it gives some warnings like:
```
2016-07-05 22:56:19,735: radical.saga.cpi    : MainProcess                     : MainThread     : WARNING : flush: [    5] [    1] (discard data: '$')
```
However, the program still runs OK.

Any clue?

**Comment by marksantcroos** [comment]
So this example doesn't work for you?
https://github.com/radical-cybertools/saga-python/blob/devel/examples/jobs/pbsjob.py

Disclaimer: it does for me.

**Comment by wjlei1990** [comment]
In my case, I need to have more complex cases, something like:
```bash
nodenames=($(uniq $PBS_NODEFILE))
node_id=0
mpirun -n 16 -host ${nodenames[$node_id]} script_run.bash -f path1.txt
node_id=$(( $node_id + 1 ))
mpirun -n 16 -host ${nodenames[$node_id]} script_run.py -f path2.txt
```
So I basically put all these commands(as string) in the `jd.excutable`. Is it the right way to do?

**Comment by marksantcroos** [comment]
> In my case, I need to have more complex cases, something like(my pbs script):

I see, thanks for providing the code in question. Can you tell me what you end up with without your fix, I still fail to see why your code is fundamentally different from the code in the example regarding escaping.

> So I basically put all these commands(as string) in the jd.excutable. Is it the right way to do?

If it works, it works ;-)
However, technically, `jd.executable` is an executable, so you would end up with:
```
jd.executable = '/bin/bash'
jd.arguments = ['-c',
'''nodenames=($(uniq $PBS_NODEFILE))
node_id=0
mpirun -n 16 -host ${nodenames[$node_id]} script_run.py -f path1.txt
node_id=$(( $node_id + 1 ))
mpirun -n 16 -host ${nodenames[$node_id]} script_run.py -f path2.txt
''']
```

**Comment by wjlei1990** [comment]
Are you say that three quotes, for example, `'''nodenames=($(uniq $PBS_NODEFILE))'''` is going to keep the `$` symbol?

**Comment by andre-merzky** [comment]
Confirmed that this differs in semantics and does not break what we have - merging.
