### ISSUE TITLE
run_job not implemented for SLURM jobs in split_module_2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#567]
Can the branch split_module_2 not submit jobs to resources using SLURM?

NotImplemented: run_job not implemented for SLURM jobs -- please construct a job description and create a job manually.

**Comment by andre-merzky** [comment]
Yeah, looks like.  Would you mind opening a SAGA ticket for that?  This should be easy to implement.  Well, if you want, you could give it a try? :)  run_job really is just a shortcut for `create_job + run`

**Comment by mingtaiha** [comment]
Sure, I'll give it a try.

**Comment by mingtaiha** [comment]
I figured it out. The problem is that [service.py](https://github.com/radical-cybertools/saga-python/blob/master/src/saga/job/service.py#L335) calls the function `run_job` instead of `run`. The function `run_job` raises an error when called.

I see the error for Stampede and Comet because they use [slurm_job.py](https://github.com/radical-cybertools/saga-python/blob/master/src/saga/adaptors/slurm/slurm_job.py#L795), which has the function `run_job` implemented, but it has not been implemented in other adaptors like pbsprojob.py.

Pull Request coming soon!

**Comment by andre-merzky** [comment]
This is implemented by now.
