### ISSUE TITLE
The LSF adaptor does not work with the default queue

### ISSUE THREAD

**Issue by joanlopez** [radical-cybertools/saga-python#568]
I'm getting a `submission failed` error when I try to submit to the default queue (without specifying one). I've been researching about the error and it seems that it comes from these lines of the adaptor's code:

```
lsf_job_id = None
for line in lines:
    if re.search('Job <.+> is submitted to queue', line):
        lsf_job_id = re.findall(r'<(.*?)>', line)[0]
        break
```
I'm getting the message below:

`Job <job_id> is submitted to default queue <queue>.`

Will be enough adding another case with this casuistic?

Thanks!

**Comment by andre-merzky** [comment]
Ah, the joys of parsing stdout messages, ey? :)  Thanks for catching this!  Yes, I think that adding another case to catch this would be the right approach at this point.  Would you be willing to give it a shot and create a pull request?  If not, let us know, and we'll take care of it!

Thanks, Andre.

PS.: github nowadays supports triple-backticks to mark a multiline block of code, like this (unescaped):

```
 \```
 code goes here
 and some more
 \```
```

**Comment by joanlopez** [comment]
Thanks for the suggestion @andre-merzky !! I'm going to make the PR :)

**Comment by marksantcroos** [comment]
Replacing
```
                if re.search('Job <.+> is submitted to queue', line):
```
with
```
                if re.search('Job <.+> is submitted to.+queue', line):
```
Should be enough I think.

**Comment by joanlopez** [comment]
Done!

Thanks :)

**Comment by marksantcroos** [comment]
Just to make sure, I assume you tried it? :)

**Comment by joanlopez** [comment]
Yes, of course! hahaha

I've made a test with the Python interpreter. I've tried both regular expressions and your suggestion works fine!

Thanks @marksantcroos :)
