### ISSUE TITLE
Could not detect shell prompt (timeout) on OSG

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#571]
Hello. I tried to submit an RP script to OSG, but RP hangs. The reason for this is that SAGA cannot detect the shell prompt on OSG. Though I did not get the SAGA level error message, I suspect that SAGA could not detect the shell prompt because the profile shows the line
```
2016-07-15 17:59:35,486: rp.session.radical.mingtha.016997.0010: umgr.scheduling.0               : MainThread     : DEBUG   : rsup.PTYShell('ssh://xd-login.opensciencegrid.org')
```
followed by a heartbeat DEBUG messages before I messages which indicated that I had manually closed the session.

I have set `SAGA_PTY_SSH_TIMEOUT=300` and yet SAGA still cannot connect to OSG. 

I at first suspected that there may be some load on the machine. Upon inspection, I found that OSG was working fine. I am able to SSH into OSG without delay, and I am able to submit jobs to OSG via `condor_submit` without problem. The Condor script queued and executed successfully.

I am using RP `feature/split_module_2`, RU `v0.41.1-12-gac72a2c@feature-raise_on`, SAGA `v0.41-40-g0754105@feature-osg_optimizations`

EDIT: More details

**Comment by mingtaiha** [comment]
The pmgr/umgr log files. Given that the pilot was not submitted to the queue, there are no agent logs

[rp.session.radical.mingtha.016997.0010.zip](https://github.com/radical-cybertools/saga-python/files/366439/rp.session.radical.mingtha.016997.0010.zip)

**Comment by mingtaiha** [comment]
Here are the log files with `RADICAL_SAGA_PTY_VERBOSE=DEBUG`

[osg_pty_timeout.txt](https://github.com/radical-cybertools/saga-python/files/378877/osg_pty_timeout.txt)

**Comment by andre-merzky** [comment]
Does this work on command line?

```
/usr/bin/env TERM=vt100 /usr/bin/ssh -t -o IdentityFile=/home/mingtha/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_mingtha_%h_%p.mha.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=300 mha@xd-login.openscienceid.org
```

**Comment by mingtaiha** [comment]
Nope. The connection timed out

**Comment by marksantcroos** [comment]
Can you remove the file that `/tmp/saga_ssh_mingtha_%h_%p.mha.ctrl` expands to and try again?

**Comment by mingtaiha** [comment]
I removed the file, but it still doesn't work. The hostname was stampede and not OSG, if that helps.

**Comment by andre-merzky** [comment]
ah: `xd-login.openscienceid.org` --> `xd-login.opensciencegrid.org`

Did you change the config file by any chance?

**Comment by mingtaiha** [comment]
Welp, this is embarrassing. I get another error for another reason, but that's for another ticket.
