### ISSUE TITLE
Accessing queue name for submitted cluster jobs

### ISSUE THREAD

**Issue by jcohen02** [radical-cybertools/saga-python#574]
Creating an issue to link with forum thread ["Accessing queue name for a submitted job"](https://groups.google.com/d/msg/saga-users/vB3r_2w3P1M/R7RFAPwgBAAJ).

When submitting a cluster job (e.g. via the PBS or TORQUE adapter), if a queue name is not provided in the job `Description` object, the cluster will route the job to a queue based on the requested job parameters. Although the queue name is shown in the output of `qstat -f` it looks like there's currently no way to access the name of the queue that the job has been routed to via saga-python.

**Comment by iparask** [comment]
There is currently no use case that requires it. Closing until such use case arises
