### ISSUE TITLE
How to get the ID a job gets when submitted to the remote machine?

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#584]
Hey, I want to get the ID of a submitted job according to the LRMS. For example, if I submit a job to Stampede and I run the command `showq -u`, I will see `JOBID`. I've checked the codebase and I don't think `saga.job.Job.get_id()` give me the LRMS job ID. Is there a way to get the LRMS Job ID from the `Job` class?

**Comment by marksantcroos** [comment]
I believe the `id` member, i.e. `myjob.id`, should give you the backend job identifier.

**Comment by marksantcroos** [comment]
Just checked, this is what I get for a job on stampede:
```
[slurm+ssh://stampede]-[7555829]
```
So you need to do some parsing.

**Comment by mingtaiha** [comment]
Ok. That's no big deal then. Thanks.
