### ISSUE TITLE
job_description in the case of reconnecting to existing jobs

### ISSUE THREAD

**Issue by j-m-r** [radical-cybertools/saga-python#585]
I'm poking at SAGA to figure out if it's what we want to use.   We have LSF 9.1.3.  I'm trying to understand what is expected to work, both "in general" and specifically with the lsf adaptor:   When I reconnect to an existing job, is there a way to get the myjob.description populated?   In particular, myjob.name?   In order for my application to use SAGA, I have to be able to find existing LSF jobs by looking at either their command+arguments or the job_name value.   From reading the SAGA code, I'm not sure if that's supported at all.

Specifically, I have this code:
`        js = saga.job.Service("lsf://localhost")

```
    ids = js.list()
    print ids
    id = ids[0]
    print "id: %s" % (id)
    myjob = js.get_job(id)
    print "Job State   : %s" % (myjob.state)
    print "Exitcode    : %s" % (myjob.exit_code)
    print "Exec. hosts : %s" % (myjob.execution_hosts)
    print "Create time : %s" % (myjob.created)
    print "Start time  : %s" % (myjob.started)
    print "End time    : %s" % (myjob.finished)
    print "Name        : %s" % (myjob.name)
    got_name = myjob.get_name()
    print "got_name %s" % got_name
```

`
I get this output:
`id: [lsf://localhost]-[1845730]
Job State   : Running
Exitcode    : None
Exec. hosts : aus-ares-04
Create time : Aug 14 23:23
Start time  : Sep 17 16:24
End time    : Sep 18 16:24
Name        : None
got_name None
`

**Comment by andre-merzky** [comment]
Hi Jim, 

would you mind giving the `feature/lsf_job_name` a quick try?  Alas, it is untested because, as said earlier,  we don't have access to an LSF cluster right now, so please bear with me in trying to fix that iteratively...

Thanks, Andre.

**Comment by andre-merzky** [comment]
Hey Jim, 

did you find the time to test that branch by any chance?

Thanks, Andre.

**Comment by andre-merzky** [comment]
Considered solved.
