### ISSUE TITLE
avoid eviction on OSG

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#589]
Reportedly, that can be achieved with 

```
Requirements = (Target.MAX.PREEMPT >= 24*60*60) || (Target.MAX.PREEMPT == false)
```

**Comment by marksantcroos** [comment]
Does it exclude sites that evict or does it change the rules of eviction?

**Comment by andre-merzky** [comment]
Alas the latter, so it might severely restrict the set of useful sites.  For some experiments it might still be useful, but for that reason it must be optional...

**Comment by marksantcroos** [comment]
You mean the former, right?

**Comment by marksantcroos** [comment]
And I agree that sometimes you might want this.

**Comment by andre-merzky** [comment]
yes, sorry - it excludes evicting sites....

...

**Comment by iparask** [comment]
There is no use case currently that uses OSG. Closing until there is one.
