### ISSUE TITLE
SAGA issue with PBSPro_13

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/saga-python#590]
Hello, 

I got troubles with pbspro adaptor while interconnecting with PBSPro 13. Adaptor fails on initialization with error: "Error running pbsnodes:"

Here is version of PBSPro:
[doleynik@login2.anselm HPC_utils]$ qstat --version
pbs_version = PBSPro_13.1.1.162303

Results of extractions: 
[doleynik@login2.anselm HPC_utils]$ unset GREP_OPTIONS; /opt/pbs/default/bin/pbsnodes -a | grep -E "(np|pcpu)[[:blank:]]*="
[doleynik@login2.anselm HPC_utils]$ 

Full debug log, pbsnodes output in attachment. 

[anselm_pbspro13.txt](https://github.com/radical-cybertools/saga-python/files/551025/anselm_pbspro13.txt)
[SAGA_anselm_debug.txt](https://github.com/radical-cybertools/saga-python/files/551026/SAGA_anselm_debug.txt)

**Comment by andre-merzky** [comment]
Hi Danila, 

Thanks for the report!  I pushed a fix (or so I hope) to the branch `fix/pbs13`.  We'll give that some testing love over the next days before releasing it -- but if you want to give it a shot before that, feel free (and let us know how it goes!)

Best, Andre.

**Comment by andre-merzky** [comment]
Hi Danila, 

did you find the time to give that branch a test?

Thanks, Andre.

**Comment by DanilaOleynik** [comment]
Hi Andre,

Yes, i had test this fix. Everything works good. More other, please find in attachment version of pbspro adaptor with recent changes for OLCF (Titan).  

Cheers,
Danila

**Comment by andre-merzky** [comment]
thanks for the feedback, we'll merge that then.

I don't see the attachment you mentioned though?

Cheers, Andre

**Comment by andre-merzky** [comment]
Hey Danila, 

thanks for the patched pbspro adaptor!  Mark noticed though that Titan is running torque, and the SAGA torque adaptor already has the relevant patch included.  Could you please switch to the torque adaptor, and report back?

I think this reconfirms that we should move to resource specific config file on the SAGA layer...
