### ISSUE TITLE
Using SAGA on OLCF's Rhea

### ISSUE THREAD

**Issue by mpbl** [radical-cybertools/saga-python#591]
Hello,

To have SAGA working properly on [Rhea](https://www.olcf.ornl.gov/support/system-user-guides/rhea-user-guide/), I had to modify the file ```[saga-install-dir]/adaptors/pbs/pbsjob.py```. Using [pbsjob.py#L312](https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/pbs/pbsjob.py#L312) as a reference, I changed:

```
    pbs_params += "#PBS -l nodes=%d:ppn=%d%s\n" % (
            nnodes, ppn, ''.join([':%s' % prop for prop in node_properties]))
```

 By:

```
    pbs_params += "#PBS -l nodes=%d\n" % (nnodes)
 ```

It is obviously not the right thing to do, but I do not know what version of pbs rhea is running and therefore cannot devise a proper ```if``` statement.

Would it be possible to add support for this version of PBS?
Let me know if you need more (or clearer) explanations.

Thanks,
Matthieu

**Comment by marksantcroos** [comment]
Hi Matthieu,

Thanks for reporting.
I should have access to Rhea, let me look into it.

Mark

**Comment by marksantcroos** [comment]
I added a special case for Rhea in the fix/rhea branch. Can you please give that a try?

**Comment by mpbl** [comment]
Hi Mark,

Thanks, it works very well when specifying the adaptor to be "torque://".
I am a bit confused about the presence of 3 different adaptors for pbs (pbs, pbspro, torque).
Is there a way for the user to know which one to pick beforehand?

Matthieu

**Comment by marksantcroos** [comment]
> Thanks, it works very well when specifying the adaptor to be "torque://".

Great.

> I am a bit confused about the presence of 3 different adaptors for pbs (pbs, pbspro, torque).
> Is there a way for the user to know which one to pick beforehand?

I understand. Originally the `pbs` adaptor covered both TORQUE and PBSPro. As they are rather distinct software systems, we splitted them into a `pbspro` and `torque` adaptor. The `pbs` adaptor is deprecated and will be removed at some point. We have a TODO item to properly communicate and effectuate this.
