### ISSUE TITLE
Trying to run command remotely using SAGA PTY layer

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#597]
I would like to run a command on Supermic remotely without making a new ssh connection. The script I am using uses RP, but Andre recommended using the SAGA PTY layer. Andre's recommendation is:

shell = sups.PTYShell (saga.Url(conf.js_url), conf.session)
ret, out, err = shell.run_sync (command)
assert (ret == 0)
print out
print err

However, when I try print `run`, I get `ret` value of `127`. I was wondering what this error is.

For arguments, I am passing an 
`rp.Session()` object to `conf.session`
`ssh://mha@supermic.cct-lsu.xsede.org` to `conf.js_url`
'qstat > ~/xsede.supermic/<session_id>_queue_load` to command. The command is to store snapshots of the status of the queue on Supermic.

Thanks,
Ming

**Comment by andre-merzky** [comment]
Is this command successful when you run it interactively on supermic?  You can check the return value with:

```
$ qstat > ~/xsede.supermic/<session_id>_queue_load`
$ echo $?
```

What do you get in `out` and `err`?

**Comment by andre-merzky** [comment]
Ping - any feedback?

**Comment by ibethune** [comment]
Doesn't sound like this will drive urgent code changes for 0.45, please correct me if I'm wrong?

**Comment by andre-merzky** [comment]
Nope, not urgent AFAICS.

**Comment by andre-merzky** [comment]
closed for inactivity.
