### ISSUE TITLE
Unable to submit jobs to Stampede or Comet (experiment/aimes)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#606]
As the title mentioned, I am unable to submit jobs to Stampede or Come using the experiment/aimes stack. Looking at the logs, I found that the problem that the class SLRUMJobService is not implemented. To my knowledge this class is for the bulk submission of jobs. Does this mean that this class needs to be implemented before I can submit a job to a SLURM LRMS using the experiment/aimes branch of SAGA?

```
2017-01-19 16:43:57,299: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 298, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 488, in _start_pilot_bulk
    jc.run()
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/task.py", line 416, in run 
    % (thread.exception, thread.traceback))
NoSuccess: thread exception: Service.run is not implemented for saga.SLURMJobService (container_run) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py +80 (wrap_function)  :  inspect.getmembers (cpi_sync_function)[15][1])))
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/threads.py", line 159, in run 
    self._result    = self._call(*self._args, **self._kwargs)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 80, in wrap_function
    inspect.getmembers (cpi_sync_function)[15][1]))
NotImplemented: Service.run is not implemented for saga.SLURMJobService (container_run) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py +80 (wrap_function)  :  inspect.getmembers (cpi_sync_function)[15][1])))
```

**Comment by andre-merzky** [comment]
This is very similar to the supermic ticket you opened: in this case it is not the `job.name` support which is missing, but rather the bulk job submission on the SAGA layer.  Please use the same stack as suggested in radical-cybertools/radical.pilot/issues/1191

**Comment by mingtaiha** [comment]
I am already using the experiment/aimes stack for RP, RU and SAGA

**Comment by andre-merzky** [comment]
that is ... surprising...  can you please send the output of `radical-stack`?  Thanks!

**Comment by andre-merzky** [comment]
oh, wait, gimme a minute, please...

**Comment by andre-merzky** [comment]
yeah, my wrong, the torque and slurm support did not quite arrive, but I only merged into the `feature/osg_optimization` branch on which the `experiment/aimes` is based.  But I will need to check with Matteo if things can be merged forward, as to not break his experiments...

**Comment by mturilli** [comment]
I think it makes sense to move the aimes branch forward as Ming's and my experiments are both within the boundaries of that project (or its follow up). Before proceeding, I would check that your bug fix of this morning works and then I would proceed. On my side, I will avoid any pull until Ming confirms that the merged version works for him on XSEDE. At that point I will pull and we will have a debug session for OSG. How does it sound?

**Comment by andre-merzky** [comment]
Sounds good to me, let us proceed like that...

**Comment by andre-merzky** [comment]
on SAGA, `aimes/experiment` is now the same as `feature/osg_optimization`, and should have bulk support for slurm and torque.  It also has all commits from devel merged.  Ming, please give this a try, and let us know how it goes!

FWIW, we have the same situation in RP, where I do not merge anything towards `experiment/aimes` from `feature/split_module_2`, to keep the experiment branch stable.  Let me know if you'd rather see thigs merged, ok?

**Comment by mingtaiha** [comment]
I tried the updated branch by submitting jobs to Stampede, Comet, and SuperMIC. I asked for 16 cores and running `/bin/true` on each core. I get the following message in stderr on my client, but the job is submitted to SLURM and the tasks runs to completion successfully. 

```
2017-01-20 01:52:36,940: radical.saga.cpi    : pmgr.launching.0                : MainThread     : ERROR   : get_name: pilot.0000
2017-01-20 01:52:36,940: radical.saga.cpi    : pmgr.launching.0                : MainThread     : ERROR   : get_name: pilot.0000
```

It takes a while waiting for the pilot once all the CUs run, but I'm assuming this is because RP is cleaning up. When I look at the `json` files, I find that the pilot and units do not reach a `DONE`state. The pilot hangs in state `PMGR_ACTIVE`. Some units reach `DONE`, but most only reach `UMGR_STAGING_OUTPUT_PENDING`. Do we have a way of to record the timings of the states?

Specific to Stampede, I always get one unit which gives following error `ssh_exchange_identification: Connection closed by remote host` in the `STDERR` of the failing unit. I'm not sure why this is the case.

**Comment by ibethune** [comment]
Tied up with the merge of split_module (next release, hopefully)

**Comment by andre-merzky** [comment]
This is merged by now.
