### ISSUE TITLE
SSH connection base path

### ISSUE THREAD

**Issue by marcoooo** [radical-cybertools/saga-python#609]
Remote base path currently setup upon ssh connexion end up in the absolute need that the remote user is a 'conrete' user. 
My exemple : we connect in our lab via ssh with a ldap login, our home is then mounted in /auto/'yourLdapLogin', SSH Context then try to use "/home/yourLdapLogin' in order to upload the wrapper.sh neede to monitor jobs.

Is there a way to change this behaviour in configuration file ? Better should be to enable to configure this directly in ssh context ?

Marc.

**Comment by marksantcroos** [comment]
I don't think we use `/home/` hardcoded anywhere, but rely on `$HOME`. What is your `$HOME` set to?

**Comment by marcoooo** [comment]
No I confirm you don't, $HOME is set to /auto/[myloginname]/ on the remote machine.
I got this error message when trying to remotly execute a simple cp command:

>  Could not detect shell prompt (timeout) (/home/marc/.virtualenvs/adaptors-core/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could n...

**Comment by marksantcroos** [comment]
Do you have a fancy prompt on the remote end? Or very verbose motd kind of messages?

**Comment by marcoooo** [comment]
I don't think so, this is standard bash shell.

**Comment by marksantcroos** [comment]
Can you paste the output of `ssh <hostname>`?

**Comment by ibethune** [comment]
Any fix for this will not make it into next week's release, once the problem is understood we can think about where to target the fix.

**Comment by marcoooo** [comment]
Sorry for my late response: here is the output upon login.
```sh
marc@marc-OptiPlex-9020:~$ ssh chakiachvi@wilkins
chakiachvi@wilkins's password: 
Last login: Fri Feb  3 14:46:56 2017 from ingeifb1.lirmm.fr
/usr/local/config/etc/.cshrc: Aucun fichier ou dossier de ce type.
[chakiachvi@wilkins ~]$ pwd
/auto/chakiachvi
```

**Comment by marksantcroos** [comment]
Your shell is csh?

**Comment by marcoooo** [comment]
```sh
[chakiachvi@wilkins ~]$ ps -p $$
  PID TTY          TIME CMD
 7352 pts/0    00:00:00 tcsh
```

This might be tcsh in fact.

**Comment by marksantcroos** [comment]
Ok, thanks. I'll refer to Andre whether we support this. Is that a conscious choice or are you just as happy to use bash?

**Comment by marcoooo** [comment]
I am afraid to say that I'll be happy to use bash, I am not responsible for the server configuration, but I'll try to come back to a more standard shell (i.e bash :-) ), I'll let you know, but in any case, does it change anything about the $HOME var not set to standard path ?

**Comment by marksantcroos** [comment]
> does it change anything about the $HOME var not set to standard path ?

No, but I also don't see anywhere that that is the problem. Where do you conclude that?

**Comment by marcoooo** [comment]
I do not know, but when using my "chakiachvi" user, job don't get run, I have another login to access the machine, with a standard user named 'phylo', which home is /home/phylo/, and when using this login / pass info over ssh, job get done. 

Be assured that it's not blocking to use saga-python, it was more like a "keep it in mind for sometime" :-)

Thanxs

**Comment by marksantcroos** [comment]
> I do not know, but when using my "chakiachvi" user, job don't get run, I have another login to access the machine,

Ah, ok, the only error message indicates a shell prompt failure.

What is the shell of user phylo?

> I am afraid to say that I'll be happy to use bash, I am not responsible for the server configuration, but I'll try to come back to a more standard shell (i.e bash :-)

You might be able to change the shell yourself with `chsh`.

> Be assured that it's not blocking to use saga-python, it was more like a "keep it in mind for sometime" :-)

Thats certainly good to know! Can you tell use a bit about your usage actually?

**Comment by marcoooo** [comment]
> What  is the shell of user phylo?

I think we found the bad guy :-) ! user "phylo" has a standard bash shell on the remote machine, I'll have a tchat with my sys-admin to change this, and let you know.

> You might be able to change the shell yourself with chsh.

No I did try and got an error message, another subject to have a look to with my sys admin.

> That's certainly good to know! Can you tell use a bit about your usage actually?

You could ask to Andre as we have been in touch last year about some more configurable options to enable the capability to use multiple various same saga adaptors with different config, as a 'per service' configuration. I am currently working (for almost a year now) on this project : https://github.com/lirmm/waves-webapp which is meant to ease publishing on the web (and on REST API) calls made to various platforms.  Have a look at the beta version here http://waves.atgc-montpellier.fr. This is currently related to executing phylogenetics jobs.

**Comment by andre-merzky** [comment]
Hey Marc & Mark :-D

glad to see that this issue is close to getting resolved!  To clarify the status of tcsh/csh support: I am quite positive that this is broken at the moment, at least in two places I can think of: setting the shell prompt and I/O redirection.  You likely stumbled over the first one.

We could invest some effort in supporting csh/tcsh, but are rather hesitant to do so: it complicates parts of the code which are too complicated already, for relatively little benefit (csh/tcsh users are rare).  So, if switching to bash resolves this for you: great :-D   But do let us know if this continues to be a problem in any way, and I'll then try to get a proper estimate of the coding effort involved.

Cheers, Andre.

**Comment by marcoooo** [comment]
Hi Andre, don't bother with this problem, as we now know from its source, tcsh...  I'll ask my sys admin why (the hell) I have this shell installed by default for my session. I think this is not really a problem, and that it can be more complicated to solve it than change my shell prompt on the server !

Regards,

**Comment by marcoooo** [comment]
I then close ticket as this is more related to my config than to saga :-D.

Thanks anyway.
