### ISSUE TITLE
Slurm:  Getting info on an external job

### ISSUE THREAD

**Issue by markperri** [radical-cybertools/saga-python#611]
Is it possible to get info on a job that was run externally?  If I want to list all jobs I have running (that were started in another program, or if this program crashed and I'm restarting it).  I create a jobservice (jscomet) and use:

ids = jsComet.list()
        for job_id in ids:
             job = jsComet.get_job(job_id)

It throws an error because there's no prev_info for this external job:

  File "/home/mark/saga-python/src/saga/adaptors/slurm/slurm_job.py", line 893, in _job_get_info
    if prev_info.get('gone', False):
AttributeError: 'NoneType' object has no attribute 'get'

I added two checks to see if prev_info exists to get around this and it seems to work fine. I can get the job state without errors.  Is there a problem with using it this way?  Should I do it another way?

Starting at line 893 in src/saga/adaptors/slurm/slurm_job.py

>        if prev_info:
            if prev_info.get('gone', False):
                self._logger.debug("Job is gone.")
                return prev_info

        # curr. info will contain the new job info collect. it starts off
        # as a copy of prev_info (don't use deepcopy because there is an API
        # object in the dict -> recursion)
        curr_info = dict()
>        if prev_info:
            curr_info['job_id'     ] = prev_info.get('job_id'     )
            curr_info['job_name'   ] = prev_info.get('job_name'   )
            curr_info['state'      ] = prev_info.get('state'      )
            curr_info['create_time'] = prev_info.get('create_time')
            curr_info['start_time' ] = prev_info.get('start_time' )
            curr_info['end_time'   ] = prev_info.get('end_time'   )
            curr_info['comp_time'  ] = prev_info.get('comp_time'  )
            curr_info['exec_hosts' ] = prev_info.get('exec_hosts' )
            curr_info['gone'       ] = prev_info.get('gone'       )

Thanks,
Mark

**Comment by marksantcroos** [comment]
In principle you should be able to reconnect to existing jobs, if that is your question.
You might have stumbled upon a bug then.

As a heads-up, our main developer is offline currently, so a more detailed reply will likely have to wait until next week.

**Comment by andre-merzky** [comment]
Yeah, that looks like a bug, thanks for the report!  Feel free to submit a pull request with the workaround you seem to have in place, we would appreciate that!

**Comment by andre-merzky** [comment]
PS.: I just saw that you joined github only recently.  Let us know if you need help creating a pull request, or if you would rather have us committing the fix! :)

**Comment by markperri** [comment]
Hi Andre and Mark,
Let me see if I can figure out the pull request.
Thanks,
Mark

**Comment by ibethune** [comment]
I propose that the PR should make it into the next release, unless it is ready in the next day or so and the changes are considered localised/low-risk.

**Comment by andre-merzky** [comment]
The PR is actually in already (#612), and is indeed both localized and low risk.  I'll give that PR a try and merge.

**Comment by andre-merzky** [comment]
Mark - this has been merged into devel now.  Would you please confirm that this works as expected, and close the ticket if so?  Thanks! :-)

**Comment by ibethune** [comment]
Hi Mark - if you have time to test this using the devel branch that would be great, otherwise we will close the ticket as the fix will be in the next release (0.45)

**Comment by markperri** [comment]
Hi Iain,
Yes, the patch works great.
Thanks,
Mark

**Comment by ibethune** [comment]
Thanks Mark!
