### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/saga-python#614]
Examples fail to run localhost. 

 This is the errror from file: bootstrap_1.err  

`
File "/home/georgeha/anaconda2/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
~   
`

**Comment by andre-merzky** [comment]
Ugh, that is a new one...

Can you please send the output of `radical-stack`?  What is your OS/version, and how was Python installed?

**Comment by andre-merzky** [comment]
Sorry, I realized only now that you have `anaconda` in your path.  Are you using an anaconda resource config?  Please check with @iparask which of those are  viable, I actually am not sure about the state of those...

**Comment by iparask** [comment]
This ticket is not about SAGA-Python. It is about RADICAL-Pilot. @georgeha, can you move the error to  RP's repo, as well as the stack?

**Comment by georgeha** [comment]
(test_ve)georgeha@js-17-215:~/radical.pilot.sandbox/rp.session.js-17-215.jetstream-cloud.org.georgeha.017210.0007-pilot.0000$ radical-stack
python            : 2.7.6
virtualenv        : /home/georgeha/test_ve
radical.utils     : v0.45.RC1@detached-v0.45.RC1
saga-python       : v0.45.RC1@detached-v0.45.RC1



[Archive.zip](https://github.com/radical-cybertools/saga-python/files/772311/Archive.zip)

**Comment by andre-merzky** [comment]
closed in favor of https://github.com/radical-cybertools/radical.pilot/issues/1211
