### ISSUE TITLE
Logging missing in async ops

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#632]
Exceptions raised in async ops are delayed, as per API spec, and need to be explicitly queried by the caller of the op.  If that for some reason cannot happen (another exception kicking in, for example), the exception is gone.  As a general rule, exceptional error conditions should be available via logging, independent of their delivery to the application.

This came up in the context of #d7ef7819e, where the exception was not available during process termination, which made finding the problem harder than it should have been.

**Comment by iparask** [comment]
I'm not sure I understand the issue. Also, I believe from the context that the issue that triggered it is resolved. This issue is closed

**Comment by andre-merzky** [comment]
This is now captured by radical-cybertools/radical.utils/issues/23
