### ISSUE TITLE
Programmatically set custom prompts

### ISSUE THREAD

**Issue by mehdisadeghi** [radical-cybertools/saga-python#635]
Is it possible to set remote shell prompt in saga to help with prompt detection? For example with an environment variable. (in this case the prompt looks like this: `➜  ~ `)

Thanks in advance!

**Comment by andre-merzky** [comment]
You can't set the prompt in SAGA, but you can change the regular expression used to detect the prompt.  For this you need a saga config file on the client side.  the config option is defined [here](https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/engine/engine.py#L66).  The config file location and syntax is documented [here](http://saga-python.readthedocs.io/en/latest/usage/config.html).

Let me know if that works for you.  We can also introduce an env variable to configure the regex.

**Comment by iparask** [comment]
There is no use case to require this.
