### ISSUE TITLE
Ability to configure find-prompt delay

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/saga-python#643]
The delay for finding a pty prompt is currently quite static, I suggest we should have an configuration variable to configure that behavior (similar to the ssh_timeout).

Here is the line where we would use the delay:

link: https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/utils/pty_shell_factory.py#L263
`./src/saga/utils/pty_shell_factory.py:263`

```
# find a prompt
                n, match = pty_shell.find (prompt_patterns, delay)
```

**Comment by iparask** [comment]
I'm not sure this is needed anymore. I'm closing the issue

**Comment by andre-merzky** [comment]
This is implemented now - set `SAGA_PTY_SSH_TIMEOUT`.
