### ISSUE TITLE
Silent failure for remote directory deletion

### ISSUE THREAD

**Issue by millingw** [radical-cybertools/saga-python#647]
I'm running an example where I specify a new working directory within a PBSPro job description, then want to delete the entire directory once the job has completed.  The working directory is automatically created and the job runs without problems, but when my script comes to remove the directory, the remove fails silently and the working directory is not deleted. I don't know if this is a bug or my code below is incorrect? 

 remote_dir = saga.filesystem.Directory(FILE_SERVICE + REMOTE_WORKING_DIR, session=session) 
 for f in remote_dir.list():
            remote_dir.remove(f)
  parent_dir = saga.filesystem.Directory(FILE_SERVICE + REMOTE_BASE_WORKING_DIR, session=session)
  parent_dir.remove(remote_dir)

**Comment by iparask** [comment]
This issue is 2 years old without any further communication. I'm closing based on the assumption that SAGA works as expected.
