### ISSUE TITLE
torque version strings

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#648]
Atlas: `6.1.1.1.h2`, changes too frequently

**Comment by DanilaOleynik** [comment]
Hi Andre.

As I can see on Titan and Blue Waters changing version of 'qstat' client does not affect PBS dialect. Probably to avoid frequent changes of code will be better to specify notation in configuration or through job service parameter? 

Cheers,
Danila

**Comment by iparask** [comment]
Closing as of age of the issue. Will reopen when a PBS system creates the same probelm

**Comment by andre-merzky** [comment]
Also, this will be addressed with the upcoming change to config files, which is captured in other tickets.
