### ISSUE TITLE
Different date timestring  format in adaptors

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/saga-python#661]
Hi,
We (me and Pavlo) found, that different adaptors uses different representation of date/time, for example: SLURM matched as '%Y-%m-%dT%H:%M:%S' and PBS/Torque - '''%a %b %d %H:%M:%S %Y". PanDA starts to use SAGA-python more widely and with different types of platform, having coomon string representation of date/time or event python datetime object will help a lot

Cheers,
Danila

**Comment by DanilaOleynik** [comment]
Hi Andre, 
Yes,  it will work good for us (almost perfect)!  

Cheers,
Danila

**Comment by andre-merzky** [comment]
Hey Danila, Pavlo, 

this should now be implemented in the `fix/issue_661` branch.  Could you please check if that behaves as expected?

Thanks!

**Comment by andre-merzky** [comment]
this is merged now.
