### ISSUE TITLE
reference to "which gsissh" in $PATH 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/saga-python#666]
I have an error when I try to `gsissh` from the `radical-VM` 
In `~/venv/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py` line `519` expects self._which ("gsissh")  but in `which.py in `radical.utils`, $PATH should be a list(): i.e. `ru.which(["gsissh"]) and therefore returns `None`. 

stack:

```
radical.pilot        : 0.47.4-merge-pre_gpu-150-gec325c89@devel
radical.utils        : 0.47.4-merge-pre_gpu-12-g4f23a6a@devel
saga                   : 0.47.3-merge-pre_gpu-24-g0fa0fb40@devel
```

**Comment by andre-merzky** [comment]
Yeah, I see  what happened there, will fix.

**Comment by lee212** [comment]
fixed and merged
