### ISSUE TITLE
SAGA does not create `-N` flag on SLURM

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/saga-python#688]
The `-N` flag is not set on the SLURM adaptor all the time. It is only setup for version `17.11.5`. I propose to setup it up for any version that is larger than that.

This is triggered by [radical.pilot issue 1754](https://github.com/radical-cybertools/radical.pilot/issues/1754).

@andre-merzky, do you agree?

**Comment by andre-merzky** [comment]
@iparask : yes, I do agree!
