### ISSUE TITLE
Create design document for RS v2

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/saga-python#713]
We will collect there some of the ideas currently documented in 'old' tickets. After copying the ideas, those tickets will be closed.

**Comment by andre-merzky** [comment]
This actually already exists [here](https://github.com/radical-cybertools/radical.pilot/wiki/Roadmap-and-Milestones) (I forgot about that page :-/).  I'll transfer the relevant ticket items there.

**Comment by andre-merzky** [comment]
SAGA Tickets have been linked.
